// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthProviders is the predicate function for authproviders builders.
type AuthProviders func(*sql.Selector)

// Demo is the predicate function for demo builders.
type Demo func(*sql.Selector)

// DepartmentLeaders is the predicate function for departmentleaders builders.
type DepartmentLeaders func(*sql.Selector)

// Departments is the predicate function for departments builders.
type Departments func(*sql.Selector)

// GroupMembership is the predicate function for groupmembership builders.
type GroupMembership func(*sql.Selector)

// Groups is the predicate function for groups builders.
type Groups func(*sql.Selector)

// Menus is the predicate function for menus builders.
type Menus func(*sql.Selector)

// Permissions is the predicate function for permissions builders.
type Permissions func(*sql.Selector)

// RoleGroupMapping is the predicate function for rolegroupmapping builders.
type RoleGroupMapping func(*sql.Selector)

// RoleMenuMapping is the predicate function for rolemenumapping builders.
type RoleMenuMapping func(*sql.Selector)

// RoleUserMapping is the predicate function for roleusermapping builders.
type RoleUserMapping func(*sql.Selector)

// Roles is the predicate function for roles builders.
type Roles func(*sql.Selector)

// SecurityKeys is the predicate function for securitykeys builders.
type SecurityKeys func(*sql.Selector)

// UserAttributes is the predicate function for userattributes builders.
type UserAttributes func(*sql.Selector)

// UserAuthLocal is the predicate function for userauthlocal builders.
type UserAuthLocal func(*sql.Selector)

// UserAuthSocial is the predicate function for userauthsocial builders.
type UserAuthSocial func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
