// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthProviders is the predicate function for authproviders builders.
type AuthProviders func(*sql.Selector)

// Credentials is the predicate function for credentials builders.
type Credentials func(*sql.Selector)

// DepartmentMembers is the predicate function for departmentmembers builders.
type DepartmentMembers func(*sql.Selector)

// Departments is the predicate function for departments builders.
type Departments func(*sql.Selector)

// GroupMembers is the predicate function for groupmembers builders.
type GroupMembers func(*sql.Selector)

// GroupRoles is the predicate function for grouproles builders.
type GroupRoles func(*sql.Selector)

// Groups is the predicate function for groups builders.
type Groups func(*sql.Selector)

// Menus is the predicate function for menus builders.
type Menus func(*sql.Selector)

// Policies is the predicate function for policies builders.
type Policies func(*sql.Selector)

// Roles is the predicate function for roles builders.
type Roles func(*sql.Selector)

// UserIdentities is the predicate function for useridentities builders.
type UserIdentities func(*sql.Selector)

// UserProfiles is the predicate function for userprofiles builders.
type UserProfiles func(*sql.Selector)

// UserRoles is the predicate function for userroles builders.
type UserRoles func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
