// Code generated by ent, DO NOT EDIT.

package authusersocial

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldUserID, v))
}

// ProviderName applies equality check predicate on the "provider_name" field. It's identical to ProviderNameEQ.
func ProviderName(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderName, v))
}

// ProviderUserID applies equality check predicate on the "provider_user_id" field. It's identical to ProviderUserIDEQ.
func ProviderUserID(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderUnionID applies equality check predicate on the "provider_union_id" field. It's identical to ProviderUnionIDEQ.
func ProviderUnionID(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderUnionID, v))
}

// AccessTokenEncrypted applies equality check predicate on the "access_token_encrypted" field. It's identical to AccessTokenEncryptedEQ.
func AccessTokenEncrypted(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// RefreshTokenEncrypted applies equality check predicate on the "refresh_token_encrypted" field. It's identical to RefreshTokenEncryptedEQ.
func RefreshTokenEncrypted(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldUserID, v))
}

// ProviderNameEQ applies the EQ predicate on the "provider_name" field.
func ProviderNameEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderName, v))
}

// ProviderNameNEQ applies the NEQ predicate on the "provider_name" field.
func ProviderNameNEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldProviderName, v))
}

// ProviderNameIn applies the In predicate on the "provider_name" field.
func ProviderNameIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldProviderName, vs...))
}

// ProviderNameNotIn applies the NotIn predicate on the "provider_name" field.
func ProviderNameNotIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldProviderName, vs...))
}

// ProviderNameGT applies the GT predicate on the "provider_name" field.
func ProviderNameGT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldProviderName, v))
}

// ProviderNameGTE applies the GTE predicate on the "provider_name" field.
func ProviderNameGTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldProviderName, v))
}

// ProviderNameLT applies the LT predicate on the "provider_name" field.
func ProviderNameLT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldProviderName, v))
}

// ProviderNameLTE applies the LTE predicate on the "provider_name" field.
func ProviderNameLTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldProviderName, v))
}

// ProviderNameContains applies the Contains predicate on the "provider_name" field.
func ProviderNameContains(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContains(FieldProviderName, v))
}

// ProviderNameHasPrefix applies the HasPrefix predicate on the "provider_name" field.
func ProviderNameHasPrefix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasPrefix(FieldProviderName, v))
}

// ProviderNameHasSuffix applies the HasSuffix predicate on the "provider_name" field.
func ProviderNameHasSuffix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasSuffix(FieldProviderName, v))
}

// ProviderNameEqualFold applies the EqualFold predicate on the "provider_name" field.
func ProviderNameEqualFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEqualFold(FieldProviderName, v))
}

// ProviderNameContainsFold applies the ContainsFold predicate on the "provider_name" field.
func ProviderNameContainsFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContainsFold(FieldProviderName, v))
}

// ProviderUserIDEQ applies the EQ predicate on the "provider_user_id" field.
func ProviderUserIDEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderUserIDNEQ applies the NEQ predicate on the "provider_user_id" field.
func ProviderUserIDNEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldProviderUserID, v))
}

// ProviderUserIDIn applies the In predicate on the "provider_user_id" field.
func ProviderUserIDIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldProviderUserID, vs...))
}

// ProviderUserIDNotIn applies the NotIn predicate on the "provider_user_id" field.
func ProviderUserIDNotIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldProviderUserID, vs...))
}

// ProviderUserIDGT applies the GT predicate on the "provider_user_id" field.
func ProviderUserIDGT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldProviderUserID, v))
}

// ProviderUserIDGTE applies the GTE predicate on the "provider_user_id" field.
func ProviderUserIDGTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldProviderUserID, v))
}

// ProviderUserIDLT applies the LT predicate on the "provider_user_id" field.
func ProviderUserIDLT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldProviderUserID, v))
}

// ProviderUserIDLTE applies the LTE predicate on the "provider_user_id" field.
func ProviderUserIDLTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldProviderUserID, v))
}

// ProviderUserIDContains applies the Contains predicate on the "provider_user_id" field.
func ProviderUserIDContains(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContains(FieldProviderUserID, v))
}

// ProviderUserIDHasPrefix applies the HasPrefix predicate on the "provider_user_id" field.
func ProviderUserIDHasPrefix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasPrefix(FieldProviderUserID, v))
}

// ProviderUserIDHasSuffix applies the HasSuffix predicate on the "provider_user_id" field.
func ProviderUserIDHasSuffix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasSuffix(FieldProviderUserID, v))
}

// ProviderUserIDEqualFold applies the EqualFold predicate on the "provider_user_id" field.
func ProviderUserIDEqualFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEqualFold(FieldProviderUserID, v))
}

// ProviderUserIDContainsFold applies the ContainsFold predicate on the "provider_user_id" field.
func ProviderUserIDContainsFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContainsFold(FieldProviderUserID, v))
}

// ProviderUnionIDEQ applies the EQ predicate on the "provider_union_id" field.
func ProviderUnionIDEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldProviderUnionID, v))
}

// ProviderUnionIDNEQ applies the NEQ predicate on the "provider_union_id" field.
func ProviderUnionIDNEQ(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldProviderUnionID, v))
}

// ProviderUnionIDIn applies the In predicate on the "provider_union_id" field.
func ProviderUnionIDIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldProviderUnionID, vs...))
}

// ProviderUnionIDNotIn applies the NotIn predicate on the "provider_union_id" field.
func ProviderUnionIDNotIn(vs ...string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldProviderUnionID, vs...))
}

// ProviderUnionIDGT applies the GT predicate on the "provider_union_id" field.
func ProviderUnionIDGT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldProviderUnionID, v))
}

// ProviderUnionIDGTE applies the GTE predicate on the "provider_union_id" field.
func ProviderUnionIDGTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldProviderUnionID, v))
}

// ProviderUnionIDLT applies the LT predicate on the "provider_union_id" field.
func ProviderUnionIDLT(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldProviderUnionID, v))
}

// ProviderUnionIDLTE applies the LTE predicate on the "provider_union_id" field.
func ProviderUnionIDLTE(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldProviderUnionID, v))
}

// ProviderUnionIDContains applies the Contains predicate on the "provider_union_id" field.
func ProviderUnionIDContains(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContains(FieldProviderUnionID, v))
}

// ProviderUnionIDHasPrefix applies the HasPrefix predicate on the "provider_union_id" field.
func ProviderUnionIDHasPrefix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasPrefix(FieldProviderUnionID, v))
}

// ProviderUnionIDHasSuffix applies the HasSuffix predicate on the "provider_union_id" field.
func ProviderUnionIDHasSuffix(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldHasSuffix(FieldProviderUnionID, v))
}

// ProviderUnionIDIsNil applies the IsNil predicate on the "provider_union_id" field.
func ProviderUnionIDIsNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIsNull(FieldProviderUnionID))
}

// ProviderUnionIDNotNil applies the NotNil predicate on the "provider_union_id" field.
func ProviderUnionIDNotNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotNull(FieldProviderUnionID))
}

// ProviderUnionIDEqualFold applies the EqualFold predicate on the "provider_union_id" field.
func ProviderUnionIDEqualFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEqualFold(FieldProviderUnionID, v))
}

// ProviderUnionIDContainsFold applies the ContainsFold predicate on the "provider_union_id" field.
func ProviderUnionIDContainsFold(v string) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldContainsFold(FieldProviderUnionID, v))
}

// AccessTokenEncryptedEQ applies the EQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedEQ(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedNEQ applies the NEQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNEQ(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIn applies the In predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIn(vs ...[]byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedNotIn applies the NotIn predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotIn(vs ...[]byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedGT applies the GT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGT(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedGTE applies the GTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGTE(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLT applies the LT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLT(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLTE applies the LTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLTE(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIsNil applies the IsNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIsNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIsNull(FieldAccessTokenEncrypted))
}

// AccessTokenEncryptedNotNil applies the NotNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotNull(FieldAccessTokenEncrypted))
}

// RefreshTokenEncryptedEQ applies the EQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEQ(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedNEQ applies the NEQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNEQ(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIn applies the In predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIn(vs ...[]byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedNotIn applies the NotIn predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotIn(vs ...[]byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedGT applies the GT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGT(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedGTE applies the GTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGTE(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLT applies the LT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLT(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLTE applies the LTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLTE(v []byte) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIsNil applies the IsNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIsNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIsNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedNotNil applies the NotNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotNull(FieldRefreshTokenEncrypted))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.FieldNotNull(FieldTokenExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthUserSocial) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthUserSocial) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthUserSocial) predicate.AuthUserSocial {
	return predicate.AuthUserSocial(sql.NotPredicates(p))
}
