// Code generated by ent, DO NOT EDIT.

package authproviders

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldUpdateTime, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldClientID, v))
}

// ClientSecretEncrypted applies equality check predicate on the "client_secret_encrypted" field. It's identical to ClientSecretEncryptedEQ.
func ClientSecretEncrypted(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldClientSecretEncrypted, v))
}

// AuthURL applies equality check predicate on the "auth_url" field. It's identical to AuthURLEQ.
func AuthURL(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldAuthURL, v))
}

// TokenURL applies equality check predicate on the "token_url" field. It's identical to TokenURLEQ.
func TokenURL(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldTokenURL, v))
}

// UserInfoURL applies equality check predicate on the "user_info_url" field. It's identical to UserInfoURLEQ.
func UserInfoURL(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldUserInfoURL, v))
}

// RedirectURL applies equality check predicate on the "redirect_url" field. It's identical to RedirectURLEQ.
func RedirectURL(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldRedirectURL, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldUpdateTime, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v Name) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v Name) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...Name) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...Name) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldName, vs...))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEncryptedEQ applies the EQ predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedNEQ applies the NEQ predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedIn applies the In predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldClientSecretEncrypted, vs...))
}

// ClientSecretEncryptedNotIn applies the NotIn predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldClientSecretEncrypted, vs...))
}

// ClientSecretEncryptedGT applies the GT predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedGTE applies the GTE predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedLT applies the LT predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedLTE applies the LTE predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedContains applies the Contains predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedHasPrefix applies the HasPrefix predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedHasSuffix applies the HasSuffix predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedEqualFold applies the EqualFold predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldClientSecretEncrypted, v))
}

// ClientSecretEncryptedContainsFold applies the ContainsFold predicate on the "client_secret_encrypted" field.
func ClientSecretEncryptedContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldClientSecretEncrypted, v))
}

// AuthURLEQ applies the EQ predicate on the "auth_url" field.
func AuthURLEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldAuthURL, v))
}

// AuthURLNEQ applies the NEQ predicate on the "auth_url" field.
func AuthURLNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldAuthURL, v))
}

// AuthURLIn applies the In predicate on the "auth_url" field.
func AuthURLIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldAuthURL, vs...))
}

// AuthURLNotIn applies the NotIn predicate on the "auth_url" field.
func AuthURLNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldAuthURL, vs...))
}

// AuthURLGT applies the GT predicate on the "auth_url" field.
func AuthURLGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldAuthURL, v))
}

// AuthURLGTE applies the GTE predicate on the "auth_url" field.
func AuthURLGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldAuthURL, v))
}

// AuthURLLT applies the LT predicate on the "auth_url" field.
func AuthURLLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldAuthURL, v))
}

// AuthURLLTE applies the LTE predicate on the "auth_url" field.
func AuthURLLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldAuthURL, v))
}

// AuthURLContains applies the Contains predicate on the "auth_url" field.
func AuthURLContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldAuthURL, v))
}

// AuthURLHasPrefix applies the HasPrefix predicate on the "auth_url" field.
func AuthURLHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldAuthURL, v))
}

// AuthURLHasSuffix applies the HasSuffix predicate on the "auth_url" field.
func AuthURLHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldAuthURL, v))
}

// AuthURLEqualFold applies the EqualFold predicate on the "auth_url" field.
func AuthURLEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldAuthURL, v))
}

// AuthURLContainsFold applies the ContainsFold predicate on the "auth_url" field.
func AuthURLContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldAuthURL, v))
}

// TokenURLEQ applies the EQ predicate on the "token_url" field.
func TokenURLEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldTokenURL, v))
}

// TokenURLNEQ applies the NEQ predicate on the "token_url" field.
func TokenURLNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldTokenURL, v))
}

// TokenURLIn applies the In predicate on the "token_url" field.
func TokenURLIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldTokenURL, vs...))
}

// TokenURLNotIn applies the NotIn predicate on the "token_url" field.
func TokenURLNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldTokenURL, vs...))
}

// TokenURLGT applies the GT predicate on the "token_url" field.
func TokenURLGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldTokenURL, v))
}

// TokenURLGTE applies the GTE predicate on the "token_url" field.
func TokenURLGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldTokenURL, v))
}

// TokenURLLT applies the LT predicate on the "token_url" field.
func TokenURLLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldTokenURL, v))
}

// TokenURLLTE applies the LTE predicate on the "token_url" field.
func TokenURLLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldTokenURL, v))
}

// TokenURLContains applies the Contains predicate on the "token_url" field.
func TokenURLContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldTokenURL, v))
}

// TokenURLHasPrefix applies the HasPrefix predicate on the "token_url" field.
func TokenURLHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldTokenURL, v))
}

// TokenURLHasSuffix applies the HasSuffix predicate on the "token_url" field.
func TokenURLHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldTokenURL, v))
}

// TokenURLEqualFold applies the EqualFold predicate on the "token_url" field.
func TokenURLEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldTokenURL, v))
}

// TokenURLContainsFold applies the ContainsFold predicate on the "token_url" field.
func TokenURLContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldTokenURL, v))
}

// UserInfoURLEQ applies the EQ predicate on the "user_info_url" field.
func UserInfoURLEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldUserInfoURL, v))
}

// UserInfoURLNEQ applies the NEQ predicate on the "user_info_url" field.
func UserInfoURLNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldUserInfoURL, v))
}

// UserInfoURLIn applies the In predicate on the "user_info_url" field.
func UserInfoURLIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldUserInfoURL, vs...))
}

// UserInfoURLNotIn applies the NotIn predicate on the "user_info_url" field.
func UserInfoURLNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldUserInfoURL, vs...))
}

// UserInfoURLGT applies the GT predicate on the "user_info_url" field.
func UserInfoURLGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldUserInfoURL, v))
}

// UserInfoURLGTE applies the GTE predicate on the "user_info_url" field.
func UserInfoURLGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldUserInfoURL, v))
}

// UserInfoURLLT applies the LT predicate on the "user_info_url" field.
func UserInfoURLLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldUserInfoURL, v))
}

// UserInfoURLLTE applies the LTE predicate on the "user_info_url" field.
func UserInfoURLLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldUserInfoURL, v))
}

// UserInfoURLContains applies the Contains predicate on the "user_info_url" field.
func UserInfoURLContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldUserInfoURL, v))
}

// UserInfoURLHasPrefix applies the HasPrefix predicate on the "user_info_url" field.
func UserInfoURLHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldUserInfoURL, v))
}

// UserInfoURLHasSuffix applies the HasSuffix predicate on the "user_info_url" field.
func UserInfoURLHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldUserInfoURL, v))
}

// UserInfoURLEqualFold applies the EqualFold predicate on the "user_info_url" field.
func UserInfoURLEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldUserInfoURL, v))
}

// UserInfoURLContainsFold applies the ContainsFold predicate on the "user_info_url" field.
func UserInfoURLContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldUserInfoURL, v))
}

// RedirectURLEQ applies the EQ predicate on the "redirect_url" field.
func RedirectURLEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEQ(FieldRedirectURL, v))
}

// RedirectURLNEQ applies the NEQ predicate on the "redirect_url" field.
func RedirectURLNEQ(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNEQ(FieldRedirectURL, v))
}

// RedirectURLIn applies the In predicate on the "redirect_url" field.
func RedirectURLIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldIn(FieldRedirectURL, vs...))
}

// RedirectURLNotIn applies the NotIn predicate on the "redirect_url" field.
func RedirectURLNotIn(vs ...string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldNotIn(FieldRedirectURL, vs...))
}

// RedirectURLGT applies the GT predicate on the "redirect_url" field.
func RedirectURLGT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGT(FieldRedirectURL, v))
}

// RedirectURLGTE applies the GTE predicate on the "redirect_url" field.
func RedirectURLGTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldGTE(FieldRedirectURL, v))
}

// RedirectURLLT applies the LT predicate on the "redirect_url" field.
func RedirectURLLT(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLT(FieldRedirectURL, v))
}

// RedirectURLLTE applies the LTE predicate on the "redirect_url" field.
func RedirectURLLTE(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldLTE(FieldRedirectURL, v))
}

// RedirectURLContains applies the Contains predicate on the "redirect_url" field.
func RedirectURLContains(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContains(FieldRedirectURL, v))
}

// RedirectURLHasPrefix applies the HasPrefix predicate on the "redirect_url" field.
func RedirectURLHasPrefix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasPrefix(FieldRedirectURL, v))
}

// RedirectURLHasSuffix applies the HasSuffix predicate on the "redirect_url" field.
func RedirectURLHasSuffix(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldHasSuffix(FieldRedirectURL, v))
}

// RedirectURLEqualFold applies the EqualFold predicate on the "redirect_url" field.
func RedirectURLEqualFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldEqualFold(FieldRedirectURL, v))
}

// RedirectURLContainsFold applies the ContainsFold predicate on the "redirect_url" field.
func RedirectURLContainsFold(v string) predicate.AuthProviders {
	return predicate.AuthProviders(sql.FieldContainsFold(FieldRedirectURL, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthProviders) predicate.AuthProviders {
	return predicate.AuthProviders(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthProviders) predicate.AuthProviders {
	return predicate.AuthProviders(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthProviders) predicate.AuthProviders {
	return predicate.AuthProviders(sql.NotPredicates(p))
}
