// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/authproviders"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// AuthProvidersUpdate is the builder for updating AuthProviders entities.
type AuthProvidersUpdate struct {
	config
	hooks    []Hook
	mutation *AuthProvidersMutation
}

// Where appends a list predicates to the AuthProvidersUpdate builder.
func (apu *AuthProvidersUpdate) Where(ps ...predicate.AuthProviders) *AuthProvidersUpdate {
	apu.mutation.Where(ps...)
	return apu
}

// SetUpdateTime sets the "update_time" field.
func (apu *AuthProvidersUpdate) SetUpdateTime(t time.Time) *AuthProvidersUpdate {
	apu.mutation.SetUpdateTime(t)
	return apu
}

// SetName sets the "name" field.
func (apu *AuthProvidersUpdate) SetName(a authproviders.Name) *AuthProvidersUpdate {
	apu.mutation.SetName(a)
	return apu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableName(a *authproviders.Name) *AuthProvidersUpdate {
	if a != nil {
		apu.SetName(*a)
	}
	return apu
}

// SetClientID sets the "client_id" field.
func (apu *AuthProvidersUpdate) SetClientID(s string) *AuthProvidersUpdate {
	apu.mutation.SetClientID(s)
	return apu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableClientID(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetClientID(*s)
	}
	return apu
}

// SetClientSecretEncrypted sets the "client_secret_encrypted" field.
func (apu *AuthProvidersUpdate) SetClientSecretEncrypted(s string) *AuthProvidersUpdate {
	apu.mutation.SetClientSecretEncrypted(s)
	return apu
}

// SetNillableClientSecretEncrypted sets the "client_secret_encrypted" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableClientSecretEncrypted(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetClientSecretEncrypted(*s)
	}
	return apu
}

// SetAuthURL sets the "auth_url" field.
func (apu *AuthProvidersUpdate) SetAuthURL(s string) *AuthProvidersUpdate {
	apu.mutation.SetAuthURL(s)
	return apu
}

// SetNillableAuthURL sets the "auth_url" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableAuthURL(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetAuthURL(*s)
	}
	return apu
}

// SetTokenURL sets the "token_url" field.
func (apu *AuthProvidersUpdate) SetTokenURL(s string) *AuthProvidersUpdate {
	apu.mutation.SetTokenURL(s)
	return apu
}

// SetNillableTokenURL sets the "token_url" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableTokenURL(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetTokenURL(*s)
	}
	return apu
}

// SetUserInfoURL sets the "user_info_url" field.
func (apu *AuthProvidersUpdate) SetUserInfoURL(s string) *AuthProvidersUpdate {
	apu.mutation.SetUserInfoURL(s)
	return apu
}

// SetNillableUserInfoURL sets the "user_info_url" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableUserInfoURL(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetUserInfoURL(*s)
	}
	return apu
}

// SetScopes sets the "scopes" field.
func (apu *AuthProvidersUpdate) SetScopes(s []string) *AuthProvidersUpdate {
	apu.mutation.SetScopes(s)
	return apu
}

// AppendScopes appends s to the "scopes" field.
func (apu *AuthProvidersUpdate) AppendScopes(s []string) *AuthProvidersUpdate {
	apu.mutation.AppendScopes(s)
	return apu
}

// SetRedirectURL sets the "redirect_url" field.
func (apu *AuthProvidersUpdate) SetRedirectURL(s string) *AuthProvidersUpdate {
	apu.mutation.SetRedirectURL(s)
	return apu
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (apu *AuthProvidersUpdate) SetNillableRedirectURL(s *string) *AuthProvidersUpdate {
	if s != nil {
		apu.SetRedirectURL(*s)
	}
	return apu
}

// Mutation returns the AuthProvidersMutation object of the builder.
func (apu *AuthProvidersUpdate) Mutation() *AuthProvidersMutation {
	return apu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (apu *AuthProvidersUpdate) Save(ctx context.Context) (int, error) {
	apu.defaults()
	return withHooks(ctx, apu.sqlSave, apu.mutation, apu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apu *AuthProvidersUpdate) SaveX(ctx context.Context) int {
	affected, err := apu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (apu *AuthProvidersUpdate) Exec(ctx context.Context) error {
	_, err := apu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apu *AuthProvidersUpdate) ExecX(ctx context.Context) {
	if err := apu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apu *AuthProvidersUpdate) defaults() {
	if _, ok := apu.mutation.UpdateTime(); !ok {
		v := authproviders.UpdateDefaultUpdateTime()
		apu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apu *AuthProvidersUpdate) check() error {
	if v, ok := apu.mutation.Name(); ok {
		if err := authproviders.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "AuthProviders.name": %w`, err)}
		}
	}
	return nil
}

func (apu *AuthProvidersUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := apu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(authproviders.Table, authproviders.Columns, sqlgraph.NewFieldSpec(authproviders.FieldID, field.TypeInt))
	if ps := apu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apu.mutation.UpdateTime(); ok {
		_spec.SetField(authproviders.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := apu.mutation.Name(); ok {
		_spec.SetField(authproviders.FieldName, field.TypeEnum, value)
	}
	if value, ok := apu.mutation.ClientID(); ok {
		_spec.SetField(authproviders.FieldClientID, field.TypeString, value)
	}
	if value, ok := apu.mutation.ClientSecretEncrypted(); ok {
		_spec.SetField(authproviders.FieldClientSecretEncrypted, field.TypeString, value)
	}
	if value, ok := apu.mutation.AuthURL(); ok {
		_spec.SetField(authproviders.FieldAuthURL, field.TypeString, value)
	}
	if value, ok := apu.mutation.TokenURL(); ok {
		_spec.SetField(authproviders.FieldTokenURL, field.TypeString, value)
	}
	if value, ok := apu.mutation.UserInfoURL(); ok {
		_spec.SetField(authproviders.FieldUserInfoURL, field.TypeString, value)
	}
	if value, ok := apu.mutation.Scopes(); ok {
		_spec.SetField(authproviders.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := apu.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authproviders.FieldScopes, value)
		})
	}
	if value, ok := apu.mutation.RedirectURL(); ok {
		_spec.SetField(authproviders.FieldRedirectURL, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, apu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authproviders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	apu.mutation.done = true
	return n, nil
}

// AuthProvidersUpdateOne is the builder for updating a single AuthProviders entity.
type AuthProvidersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthProvidersMutation
}

// SetUpdateTime sets the "update_time" field.
func (apuo *AuthProvidersUpdateOne) SetUpdateTime(t time.Time) *AuthProvidersUpdateOne {
	apuo.mutation.SetUpdateTime(t)
	return apuo
}

// SetName sets the "name" field.
func (apuo *AuthProvidersUpdateOne) SetName(a authproviders.Name) *AuthProvidersUpdateOne {
	apuo.mutation.SetName(a)
	return apuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableName(a *authproviders.Name) *AuthProvidersUpdateOne {
	if a != nil {
		apuo.SetName(*a)
	}
	return apuo
}

// SetClientID sets the "client_id" field.
func (apuo *AuthProvidersUpdateOne) SetClientID(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetClientID(s)
	return apuo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableClientID(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetClientID(*s)
	}
	return apuo
}

// SetClientSecretEncrypted sets the "client_secret_encrypted" field.
func (apuo *AuthProvidersUpdateOne) SetClientSecretEncrypted(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetClientSecretEncrypted(s)
	return apuo
}

// SetNillableClientSecretEncrypted sets the "client_secret_encrypted" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableClientSecretEncrypted(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetClientSecretEncrypted(*s)
	}
	return apuo
}

// SetAuthURL sets the "auth_url" field.
func (apuo *AuthProvidersUpdateOne) SetAuthURL(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetAuthURL(s)
	return apuo
}

// SetNillableAuthURL sets the "auth_url" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableAuthURL(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetAuthURL(*s)
	}
	return apuo
}

// SetTokenURL sets the "token_url" field.
func (apuo *AuthProvidersUpdateOne) SetTokenURL(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetTokenURL(s)
	return apuo
}

// SetNillableTokenURL sets the "token_url" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableTokenURL(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetTokenURL(*s)
	}
	return apuo
}

// SetUserInfoURL sets the "user_info_url" field.
func (apuo *AuthProvidersUpdateOne) SetUserInfoURL(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetUserInfoURL(s)
	return apuo
}

// SetNillableUserInfoURL sets the "user_info_url" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableUserInfoURL(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetUserInfoURL(*s)
	}
	return apuo
}

// SetScopes sets the "scopes" field.
func (apuo *AuthProvidersUpdateOne) SetScopes(s []string) *AuthProvidersUpdateOne {
	apuo.mutation.SetScopes(s)
	return apuo
}

// AppendScopes appends s to the "scopes" field.
func (apuo *AuthProvidersUpdateOne) AppendScopes(s []string) *AuthProvidersUpdateOne {
	apuo.mutation.AppendScopes(s)
	return apuo
}

// SetRedirectURL sets the "redirect_url" field.
func (apuo *AuthProvidersUpdateOne) SetRedirectURL(s string) *AuthProvidersUpdateOne {
	apuo.mutation.SetRedirectURL(s)
	return apuo
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (apuo *AuthProvidersUpdateOne) SetNillableRedirectURL(s *string) *AuthProvidersUpdateOne {
	if s != nil {
		apuo.SetRedirectURL(*s)
	}
	return apuo
}

// Mutation returns the AuthProvidersMutation object of the builder.
func (apuo *AuthProvidersUpdateOne) Mutation() *AuthProvidersMutation {
	return apuo.mutation
}

// Where appends a list predicates to the AuthProvidersUpdate builder.
func (apuo *AuthProvidersUpdateOne) Where(ps ...predicate.AuthProviders) *AuthProvidersUpdateOne {
	apuo.mutation.Where(ps...)
	return apuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (apuo *AuthProvidersUpdateOne) Select(field string, fields ...string) *AuthProvidersUpdateOne {
	apuo.fields = append([]string{field}, fields...)
	return apuo
}

// Save executes the query and returns the updated AuthProviders entity.
func (apuo *AuthProvidersUpdateOne) Save(ctx context.Context) (*AuthProviders, error) {
	apuo.defaults()
	return withHooks(ctx, apuo.sqlSave, apuo.mutation, apuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apuo *AuthProvidersUpdateOne) SaveX(ctx context.Context) *AuthProviders {
	node, err := apuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (apuo *AuthProvidersUpdateOne) Exec(ctx context.Context) error {
	_, err := apuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apuo *AuthProvidersUpdateOne) ExecX(ctx context.Context) {
	if err := apuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apuo *AuthProvidersUpdateOne) defaults() {
	if _, ok := apuo.mutation.UpdateTime(); !ok {
		v := authproviders.UpdateDefaultUpdateTime()
		apuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apuo *AuthProvidersUpdateOne) check() error {
	if v, ok := apuo.mutation.Name(); ok {
		if err := authproviders.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "AuthProviders.name": %w`, err)}
		}
	}
	return nil
}

func (apuo *AuthProvidersUpdateOne) sqlSave(ctx context.Context) (_node *AuthProviders, err error) {
	if err := apuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authproviders.Table, authproviders.Columns, sqlgraph.NewFieldSpec(authproviders.FieldID, field.TypeInt))
	id, ok := apuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "AuthProviders.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := apuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authproviders.FieldID)
		for _, f := range fields {
			if !authproviders.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != authproviders.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := apuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apuo.mutation.UpdateTime(); ok {
		_spec.SetField(authproviders.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := apuo.mutation.Name(); ok {
		_spec.SetField(authproviders.FieldName, field.TypeEnum, value)
	}
	if value, ok := apuo.mutation.ClientID(); ok {
		_spec.SetField(authproviders.FieldClientID, field.TypeString, value)
	}
	if value, ok := apuo.mutation.ClientSecretEncrypted(); ok {
		_spec.SetField(authproviders.FieldClientSecretEncrypted, field.TypeString, value)
	}
	if value, ok := apuo.mutation.AuthURL(); ok {
		_spec.SetField(authproviders.FieldAuthURL, field.TypeString, value)
	}
	if value, ok := apuo.mutation.TokenURL(); ok {
		_spec.SetField(authproviders.FieldTokenURL, field.TypeString, value)
	}
	if value, ok := apuo.mutation.UserInfoURL(); ok {
		_spec.SetField(authproviders.FieldUserInfoURL, field.TypeString, value)
	}
	if value, ok := apuo.mutation.Scopes(); ok {
		_spec.SetField(authproviders.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := apuo.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authproviders.FieldScopes, value)
		})
	}
	if value, ok := apuo.mutation.RedirectURL(); ok {
		_spec.SetField(authproviders.FieldRedirectURL, field.TypeString, value)
	}
	_node = &AuthProviders{config: apuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, apuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authproviders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	apuo.mutation.done = true
	return _node, nil
}
