// Code generated by ent, DO NOT EDIT.

package lion

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/authproviders"
)

// AuthProviders is the model entity for the AuthProviders schema.
type AuthProviders struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 认证提供方名称
	Name string `json:"name,omitempty"`
	// 支持的认证提供方
	Type authproviders.Type `json:"type,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ClientSecretEncrypted holds the value of the "client_secret_encrypted" field.
	ClientSecretEncrypted []byte `json:"-"`
	// Scopes holds the value of the "scopes" field.
	Scopes string `json:"scopes,omitempty"`
	// RedirectURI holds the value of the "redirect_uri" field.
	RedirectURI string `json:"redirect_uri,omitempty"`
	// Issuer holds the value of the "issuer" field.
	Issuer string `json:"issuer,omitempty"`
	// AuthorizationEndpoint holds the value of the "authorization_endpoint" field.
	AuthorizationEndpoint string `json:"authorization_endpoint,omitempty"`
	// TokenEndpoint holds the value of the "token_endpoint" field.
	TokenEndpoint string `json:"token_endpoint,omitempty"`
	// UserinfoEndpoint holds the value of the "userinfo_endpoint" field.
	UserinfoEndpoint string `json:"userinfo_endpoint,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthProviders) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authproviders.FieldClientSecretEncrypted:
			values[i] = new([]byte)
		case authproviders.FieldEnabled:
			values[i] = new(sql.NullBool)
		case authproviders.FieldID:
			values[i] = new(sql.NullInt64)
		case authproviders.FieldName, authproviders.FieldType, authproviders.FieldClientID, authproviders.FieldScopes, authproviders.FieldRedirectURI, authproviders.FieldIssuer, authproviders.FieldAuthorizationEndpoint, authproviders.FieldTokenEndpoint, authproviders.FieldUserinfoEndpoint:
			values[i] = new(sql.NullString)
		case authproviders.FieldCreatedAt, authproviders.FieldUpdatedAt, authproviders.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthProviders fields.
func (ap *AuthProviders) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authproviders.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ap.ID = int(value.Int64)
		case authproviders.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ap.CreatedAt = value.Time
			}
		case authproviders.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ap.UpdatedAt = value.Time
			}
		case authproviders.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ap.DeletedAt = new(time.Time)
				*ap.DeletedAt = value.Time
			}
		case authproviders.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ap.Name = value.String
			}
		case authproviders.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				ap.Type = authproviders.Type(value.String)
			}
		case authproviders.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				ap.ClientID = value.String
			}
		case authproviders.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				ap.Enabled = value.Bool
			}
		case authproviders.FieldClientSecretEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field client_secret_encrypted", values[i])
			} else if value != nil {
				ap.ClientSecretEncrypted = *value
			}
		case authproviders.FieldScopes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value.Valid {
				ap.Scopes = value.String
			}
		case authproviders.FieldRedirectURI:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_uri", values[i])
			} else if value.Valid {
				ap.RedirectURI = value.String
			}
		case authproviders.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				ap.Issuer = value.String
			}
		case authproviders.FieldAuthorizationEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authorization_endpoint", values[i])
			} else if value.Valid {
				ap.AuthorizationEndpoint = value.String
			}
		case authproviders.FieldTokenEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_endpoint", values[i])
			} else if value.Valid {
				ap.TokenEndpoint = value.String
			}
		case authproviders.FieldUserinfoEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userinfo_endpoint", values[i])
			} else if value.Valid {
				ap.UserinfoEndpoint = value.String
			}
		default:
			ap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthProviders.
// This includes values selected through modifiers, order, etc.
func (ap *AuthProviders) Value(name string) (ent.Value, error) {
	return ap.selectValues.Get(name)
}

// Update returns a builder for updating this AuthProviders.
// Note that you need to call AuthProviders.Unwrap() before calling this method if this AuthProviders
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *AuthProviders) Update() *AuthProvidersUpdateOne {
	return NewAuthProvidersClient(ap.config).UpdateOne(ap)
}

// Unwrap unwraps the AuthProviders entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *AuthProviders) Unwrap() *AuthProviders {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("lion: AuthProviders is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *AuthProviders) String() string {
	var builder strings.Builder
	builder.WriteString("AuthProviders(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ap.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ap.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ap.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(ap.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", ap.Type))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(ap.ClientID)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", ap.Enabled))
	builder.WriteString(", ")
	builder.WriteString("client_secret_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(ap.Scopes)
	builder.WriteString(", ")
	builder.WriteString("redirect_uri=")
	builder.WriteString(ap.RedirectURI)
	builder.WriteString(", ")
	builder.WriteString("issuer=")
	builder.WriteString(ap.Issuer)
	builder.WriteString(", ")
	builder.WriteString("authorization_endpoint=")
	builder.WriteString(ap.AuthorizationEndpoint)
	builder.WriteString(", ")
	builder.WriteString("token_endpoint=")
	builder.WriteString(ap.TokenEndpoint)
	builder.WriteString(", ")
	builder.WriteString("userinfo_endpoint=")
	builder.WriteString(ap.UserinfoEndpoint)
	builder.WriteByte(')')
	return builder.String()
}

// AuthProvidersSlice is a parsable slice of AuthProviders.
type AuthProvidersSlice []*AuthProviders
