// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/credentials"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// CredentialsUpdate is the builder for updating Credentials entities.
type CredentialsUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialsMutation
}

// Where appends a list predicates to the CredentialsUpdate builder.
func (_u *CredentialsUpdate) Where(ps ...predicate.Credentials) *CredentialsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialsUpdate) SetUpdatedAt(v time.Time) *CredentialsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CredentialsUpdate) SetCreatedBy(v int64) *CredentialsUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableCreatedBy(v *int64) *CredentialsUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *CredentialsUpdate) AddCreatedBy(v int64) *CredentialsUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *CredentialsUpdate) SetUpdatedBy(v int64) *CredentialsUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableUpdatedBy(v *int64) *CredentialsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *CredentialsUpdate) AddUpdatedBy(v int64) *CredentialsUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialsUpdate) SetName(v string) *CredentialsUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableName(v *string) *CredentialsUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CredentialsUpdate) SetType(v int) *CredentialsUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableType(v *int) *CredentialsUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *CredentialsUpdate) AddType(v int) *CredentialsUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetAppid sets the "appid" field.
func (_u *CredentialsUpdate) SetAppid(v string) *CredentialsUpdate {
	_u.mutation.SetAppid(v)
	return _u
}

// SetNillableAppid sets the "appid" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableAppid(v *string) *CredentialsUpdate {
	if v != nil {
		_u.SetAppid(*v)
	}
	return _u
}

// SetAppkeyEncrypted sets the "appkey_encrypted" field.
func (_u *CredentialsUpdate) SetAppkeyEncrypted(v []byte) *CredentialsUpdate {
	_u.mutation.SetAppkeyEncrypted(v)
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *CredentialsUpdate) SetPublicKey(v string) *CredentialsUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillablePublicKey(v *string) *CredentialsUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetPrivateKeyEncrypted sets the "private_key_encrypted" field.
func (_u *CredentialsUpdate) SetPrivateKeyEncrypted(v []byte) *CredentialsUpdate {
	_u.mutation.SetPrivateKeyEncrypted(v)
	return _u
}

// SetUsage sets the "usage" field.
func (_u *CredentialsUpdate) SetUsage(v string) *CredentialsUpdate {
	_u.mutation.SetUsage(v)
	return _u
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableUsage(v *string) *CredentialsUpdate {
	if v != nil {
		_u.SetUsage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CredentialsUpdate) SetExpiresAt(v time.Time) *CredentialsUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CredentialsUpdate) SetNillableExpiresAt(v *time.Time) *CredentialsUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CredentialsUpdate) ClearExpiresAt() *CredentialsUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the CredentialsMutation object of the builder.
func (_u *CredentialsUpdate) Mutation() *CredentialsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentials.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CredentialsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(credentials.Table, credentials.Columns, sqlgraph.NewFieldSpec(credentials.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentials.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(credentials.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(credentials.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(credentials.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(credentials.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentials.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(credentials.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(credentials.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Appid(); ok {
		_spec.SetField(credentials.FieldAppid, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppkeyEncrypted(); ok {
		_spec.SetField(credentials.FieldAppkeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(credentials.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		_spec.SetField(credentials.FieldPrivateKeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(credentials.FieldUsage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(credentials.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(credentials.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentials.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialsUpdateOne is the builder for updating a single Credentials entity.
type CredentialsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialsUpdateOne) SetUpdatedAt(v time.Time) *CredentialsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CredentialsUpdateOne) SetCreatedBy(v int64) *CredentialsUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableCreatedBy(v *int64) *CredentialsUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *CredentialsUpdateOne) AddCreatedBy(v int64) *CredentialsUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *CredentialsUpdateOne) SetUpdatedBy(v int64) *CredentialsUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableUpdatedBy(v *int64) *CredentialsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *CredentialsUpdateOne) AddUpdatedBy(v int64) *CredentialsUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CredentialsUpdateOne) SetName(v string) *CredentialsUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableName(v *string) *CredentialsUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CredentialsUpdateOne) SetType(v int) *CredentialsUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableType(v *int) *CredentialsUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *CredentialsUpdateOne) AddType(v int) *CredentialsUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetAppid sets the "appid" field.
func (_u *CredentialsUpdateOne) SetAppid(v string) *CredentialsUpdateOne {
	_u.mutation.SetAppid(v)
	return _u
}

// SetNillableAppid sets the "appid" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableAppid(v *string) *CredentialsUpdateOne {
	if v != nil {
		_u.SetAppid(*v)
	}
	return _u
}

// SetAppkeyEncrypted sets the "appkey_encrypted" field.
func (_u *CredentialsUpdateOne) SetAppkeyEncrypted(v []byte) *CredentialsUpdateOne {
	_u.mutation.SetAppkeyEncrypted(v)
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *CredentialsUpdateOne) SetPublicKey(v string) *CredentialsUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillablePublicKey(v *string) *CredentialsUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetPrivateKeyEncrypted sets the "private_key_encrypted" field.
func (_u *CredentialsUpdateOne) SetPrivateKeyEncrypted(v []byte) *CredentialsUpdateOne {
	_u.mutation.SetPrivateKeyEncrypted(v)
	return _u
}

// SetUsage sets the "usage" field.
func (_u *CredentialsUpdateOne) SetUsage(v string) *CredentialsUpdateOne {
	_u.mutation.SetUsage(v)
	return _u
}

// SetNillableUsage sets the "usage" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableUsage(v *string) *CredentialsUpdateOne {
	if v != nil {
		_u.SetUsage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CredentialsUpdateOne) SetExpiresAt(v time.Time) *CredentialsUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CredentialsUpdateOne) SetNillableExpiresAt(v *time.Time) *CredentialsUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *CredentialsUpdateOne) ClearExpiresAt() *CredentialsUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the CredentialsMutation object of the builder.
func (_u *CredentialsUpdateOne) Mutation() *CredentialsMutation {
	return _u.mutation
}

// Where appends a list predicates to the CredentialsUpdate builder.
func (_u *CredentialsUpdateOne) Where(ps ...predicate.Credentials) *CredentialsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialsUpdateOne) Select(field string, fields ...string) *CredentialsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Credentials entity.
func (_u *CredentialsUpdateOne) Save(ctx context.Context) (*Credentials, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialsUpdateOne) SaveX(ctx context.Context) *Credentials {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentials.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CredentialsUpdateOne) sqlSave(ctx context.Context) (_node *Credentials, err error) {
	_spec := sqlgraph.NewUpdateSpec(credentials.Table, credentials.Columns, sqlgraph.NewFieldSpec(credentials.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "Credentials.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentials.FieldID)
		for _, f := range fields {
			if !credentials.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != credentials.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentials.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(credentials.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(credentials.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(credentials.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(credentials.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(credentials.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(credentials.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(credentials.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Appid(); ok {
		_spec.SetField(credentials.FieldAppid, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppkeyEncrypted(); ok {
		_spec.SetField(credentials.FieldAppkeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(credentials.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyEncrypted(); ok {
		_spec.SetField(credentials.FieldPrivateKeyEncrypted, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(credentials.FieldUsage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(credentials.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(credentials.FieldExpiresAt, field.TypeTime)
	}
	_node = &Credentials{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentials.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
