// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/demo"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// DemoUpdate is the builder for updating Demo entities.
type DemoUpdate struct {
	config
	hooks    []Hook
	mutation *DemoMutation
}

// Where appends a list predicates to the DemoUpdate builder.
func (du *DemoUpdate) Where(ps ...predicate.Demo) *DemoUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUpdateTime sets the "update_time" field.
func (du *DemoUpdate) SetUpdateTime(t time.Time) *DemoUpdate {
	du.mutation.SetUpdateTime(t)
	return du
}

// SetName sets the "name" field.
func (du *DemoUpdate) SetName(s string) *DemoUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DemoUpdate) SetNillableName(s *string) *DemoUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// Mutation returns the DemoMutation object of the builder.
func (du *DemoUpdate) Mutation() *DemoMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DemoUpdate) Save(ctx context.Context) (int, error) {
	du.defaults()
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DemoUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DemoUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DemoUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DemoUpdate) defaults() {
	if _, ok := du.mutation.UpdateTime(); !ok {
		v := demo.UpdateDefaultUpdateTime()
		du.mutation.SetUpdateTime(v)
	}
}

func (du *DemoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(demo.Table, demo.Columns, sqlgraph.NewFieldSpec(demo.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UpdateTime(); ok {
		_spec.SetField(demo.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(demo.FieldName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{demo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DemoUpdateOne is the builder for updating a single Demo entity.
type DemoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DemoMutation
}

// SetUpdateTime sets the "update_time" field.
func (duo *DemoUpdateOne) SetUpdateTime(t time.Time) *DemoUpdateOne {
	duo.mutation.SetUpdateTime(t)
	return duo
}

// SetName sets the "name" field.
func (duo *DemoUpdateOne) SetName(s string) *DemoUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DemoUpdateOne) SetNillableName(s *string) *DemoUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// Mutation returns the DemoMutation object of the builder.
func (duo *DemoUpdateOne) Mutation() *DemoMutation {
	return duo.mutation
}

// Where appends a list predicates to the DemoUpdate builder.
func (duo *DemoUpdateOne) Where(ps ...predicate.Demo) *DemoUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DemoUpdateOne) Select(field string, fields ...string) *DemoUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Demo entity.
func (duo *DemoUpdateOne) Save(ctx context.Context) (*Demo, error) {
	duo.defaults()
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DemoUpdateOne) SaveX(ctx context.Context) *Demo {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DemoUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DemoUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DemoUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdateTime(); !ok {
		v := demo.UpdateDefaultUpdateTime()
		duo.mutation.SetUpdateTime(v)
	}
}

func (duo *DemoUpdateOne) sqlSave(ctx context.Context) (_node *Demo, err error) {
	_spec := sqlgraph.NewUpdateSpec(demo.Table, demo.Columns, sqlgraph.NewFieldSpec(demo.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "Demo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, demo.FieldID)
		for _, f := range fields {
			if !demo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != demo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UpdateTime(); ok {
		_spec.SetField(demo.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(demo.FieldName, field.TypeString, value)
	}
	_node = &Demo{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{demo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
