// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/departments"
	"github.com/grpc-kit/pkg/lion/groups"
	"github.com/grpc-kit/pkg/lion/roledepartments"
	"github.com/grpc-kit/pkg/lion/userdepartments"
)

// DepartmentsCreate is the builder for creating a Departments entity.
type DepartmentsCreate struct {
	config
	mutation *DepartmentsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DepartmentsCreate) SetCreatedAt(v time.Time) *DepartmentsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableCreatedAt(v *time.Time) *DepartmentsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DepartmentsCreate) SetUpdatedAt(v time.Time) *DepartmentsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableUpdatedAt(v *time.Time) *DepartmentsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DepartmentsCreate) SetDeletedAt(v time.Time) *DepartmentsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableDeletedAt(v *time.Time) *DepartmentsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DepartmentsCreate) SetCreatedBy(v int64) *DepartmentsCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableCreatedBy(v *int64) *DepartmentsCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DepartmentsCreate) SetUpdatedBy(v int64) *DepartmentsCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableUpdatedBy(v *int64) *DepartmentsCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *DepartmentsCreate) SetParentID(v int) *DepartmentsCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableParentID(v *int) *DepartmentsCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DepartmentsCreate) SetName(v string) *DepartmentsCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetI18nName sets the "i18n_name" field.
func (_c *DepartmentsCreate) SetI18nName(v map[string]string) *DepartmentsCreate {
	_c.mutation.SetI18nName(v)
	return _c
}

// SetDepartmentType sets the "department_type" field.
func (_c *DepartmentsCreate) SetDepartmentType(v int) *DepartmentsCreate {
	_c.mutation.SetDepartmentType(v)
	return _c
}

// SetNillableDepartmentType sets the "department_type" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableDepartmentType(v *int) *DepartmentsCreate {
	if v != nil {
		_c.SetDepartmentType(*v)
	}
	return _c
}

// SetDepartmentStatus sets the "department_status" field.
func (_c *DepartmentsCreate) SetDepartmentStatus(v int) *DepartmentsCreate {
	_c.mutation.SetDepartmentStatus(v)
	return _c
}

// SetNillableDepartmentStatus sets the "department_status" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableDepartmentStatus(v *int) *DepartmentsCreate {
	if v != nil {
		_c.SetDepartmentStatus(*v)
	}
	return _c
}

// SetOrderWeight sets the "order_weight" field.
func (_c *DepartmentsCreate) SetOrderWeight(v int) *DepartmentsCreate {
	_c.mutation.SetOrderWeight(v)
	return _c
}

// SetNillableOrderWeight sets the "order_weight" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableOrderWeight(v *int) *DepartmentsCreate {
	if v != nil {
		_c.SetOrderWeight(*v)
	}
	return _c
}

// SetEmailEncrypted sets the "email_encrypted" field.
func (_c *DepartmentsCreate) SetEmailEncrypted(v []byte) *DepartmentsCreate {
	_c.mutation.SetEmailEncrypted(v)
	return _c
}

// SetPhoneNumberEncrypted sets the "phone_number_encrypted" field.
func (_c *DepartmentsCreate) SetPhoneNumberEncrypted(v []byte) *DepartmentsCreate {
	_c.mutation.SetPhoneNumberEncrypted(v)
	return _c
}

// SetAddressEncrypted sets the "address_encrypted" field.
func (_c *DepartmentsCreate) SetAddressEncrypted(v []byte) *DepartmentsCreate {
	_c.mutation.SetAddressEncrypted(v)
	return _c
}

// SetCostCenterCode sets the "cost_center_code" field.
func (_c *DepartmentsCreate) SetCostCenterCode(v string) *DepartmentsCreate {
	_c.mutation.SetCostCenterCode(v)
	return _c
}

// SetNillableCostCenterCode sets the "cost_center_code" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableCostCenterCode(v *string) *DepartmentsCreate {
	if v != nil {
		_c.SetCostCenterCode(*v)
	}
	return _c
}

// SetBudgetItemCode sets the "budget_item_code" field.
func (_c *DepartmentsCreate) SetBudgetItemCode(v string) *DepartmentsCreate {
	_c.mutation.SetBudgetItemCode(v)
	return _c
}

// SetNillableBudgetItemCode sets the "budget_item_code" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableBudgetItemCode(v *string) *DepartmentsCreate {
	if v != nil {
		_c.SetBudgetItemCode(*v)
	}
	return _c
}

// SetMaxMembers sets the "max_members" field.
func (_c *DepartmentsCreate) SetMaxMembers(v int) *DepartmentsCreate {
	_c.mutation.SetMaxMembers(v)
	return _c
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableMaxMembers(v *int) *DepartmentsCreate {
	if v != nil {
		_c.SetMaxMembers(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *DepartmentsCreate) SetExternalID(v string) *DepartmentsCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableExternalID(v *string) *DepartmentsCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DepartmentsCreate) SetMetadata(v map[string]string) *DepartmentsCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DepartmentsCreate) SetDescription(v string) *DepartmentsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DepartmentsCreate) SetNillableDescription(v *string) *DepartmentsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddLionRoleDepartmentIDs adds the "lion_role_departments" edge to the RoleDepartments entity by IDs.
func (_c *DepartmentsCreate) AddLionRoleDepartmentIDs(ids ...int) *DepartmentsCreate {
	_c.mutation.AddLionRoleDepartmentIDs(ids...)
	return _c
}

// AddLionRoleDepartments adds the "lion_role_departments" edges to the RoleDepartments entity.
func (_c *DepartmentsCreate) AddLionRoleDepartments(v ...*RoleDepartments) *DepartmentsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLionRoleDepartmentIDs(ids...)
}

// AddLionUserDepartmentIDs adds the "lion_user_departments" edge to the UserDepartments entity by IDs.
func (_c *DepartmentsCreate) AddLionUserDepartmentIDs(ids ...int) *DepartmentsCreate {
	_c.mutation.AddLionUserDepartmentIDs(ids...)
	return _c
}

// AddLionUserDepartments adds the "lion_user_departments" edges to the UserDepartments entity.
func (_c *DepartmentsCreate) AddLionUserDepartments(v ...*UserDepartments) *DepartmentsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLionUserDepartmentIDs(ids...)
}

// AddLionGroupIDs adds the "lion_groups" edge to the Groups entity by IDs.
func (_c *DepartmentsCreate) AddLionGroupIDs(ids ...int) *DepartmentsCreate {
	_c.mutation.AddLionGroupIDs(ids...)
	return _c
}

// AddLionGroups adds the "lion_groups" edges to the Groups entity.
func (_c *DepartmentsCreate) AddLionGroups(v ...*Groups) *DepartmentsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLionGroupIDs(ids...)
}

// Mutation returns the DepartmentsMutation object of the builder.
func (_c *DepartmentsCreate) Mutation() *DepartmentsMutation {
	return _c.mutation
}

// Save creates the Departments in the database.
func (_c *DepartmentsCreate) Save(ctx context.Context) (*Departments, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepartmentsCreate) SaveX(ctx context.Context) *Departments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepartmentsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := departments.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := departments.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := departments.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		v := departments.DefaultUpdatedBy
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := departments.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.DepartmentType(); !ok {
		v := departments.DefaultDepartmentType
		_c.mutation.SetDepartmentType(v)
	}
	if _, ok := _c.mutation.DepartmentStatus(); !ok {
		v := departments.DefaultDepartmentStatus
		_c.mutation.SetDepartmentStatus(v)
	}
	if _, ok := _c.mutation.OrderWeight(); !ok {
		v := departments.DefaultOrderWeight
		_c.mutation.SetOrderWeight(v)
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		v := departments.DefaultMaxMembers
		_c.mutation.SetMaxMembers(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := departments.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepartmentsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "Departments.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "Departments.updated_at"`)}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`lion: missing required field "Departments.parent_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`lion: missing required field "Departments.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := departments.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "Departments.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DepartmentType(); !ok {
		return &ValidationError{Name: "department_type", err: errors.New(`lion: missing required field "Departments.department_type"`)}
	}
	if _, ok := _c.mutation.DepartmentStatus(); !ok {
		return &ValidationError{Name: "department_status", err: errors.New(`lion: missing required field "Departments.department_status"`)}
	}
	if _, ok := _c.mutation.OrderWeight(); !ok {
		return &ValidationError{Name: "order_weight", err: errors.New(`lion: missing required field "Departments.order_weight"`)}
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		return &ValidationError{Name: "max_members", err: errors.New(`lion: missing required field "Departments.max_members"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`lion: missing required field "Departments.description"`)}
	}
	return nil
}

func (_c *DepartmentsCreate) sqlSave(ctx context.Context) (*Departments, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DepartmentsCreate) createSpec() (*Departments, *sqlgraph.CreateSpec) {
	var (
		_node = &Departments{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(departments.Table, sqlgraph.NewFieldSpec(departments.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(departments.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(departments.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(departments.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(departments.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(departments.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(departments.FieldParentID, field.TypeInt, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(departments.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.I18nName(); ok {
		_spec.SetField(departments.FieldI18nName, field.TypeJSON, value)
		_node.I18nName = value
	}
	if value, ok := _c.mutation.DepartmentType(); ok {
		_spec.SetField(departments.FieldDepartmentType, field.TypeInt, value)
		_node.DepartmentType = value
	}
	if value, ok := _c.mutation.DepartmentStatus(); ok {
		_spec.SetField(departments.FieldDepartmentStatus, field.TypeInt, value)
		_node.DepartmentStatus = value
	}
	if value, ok := _c.mutation.OrderWeight(); ok {
		_spec.SetField(departments.FieldOrderWeight, field.TypeInt, value)
		_node.OrderWeight = value
	}
	if value, ok := _c.mutation.EmailEncrypted(); ok {
		_spec.SetField(departments.FieldEmailEncrypted, field.TypeBytes, value)
		_node.EmailEncrypted = value
	}
	if value, ok := _c.mutation.PhoneNumberEncrypted(); ok {
		_spec.SetField(departments.FieldPhoneNumberEncrypted, field.TypeBytes, value)
		_node.PhoneNumberEncrypted = value
	}
	if value, ok := _c.mutation.AddressEncrypted(); ok {
		_spec.SetField(departments.FieldAddressEncrypted, field.TypeBytes, value)
		_node.AddressEncrypted = value
	}
	if value, ok := _c.mutation.CostCenterCode(); ok {
		_spec.SetField(departments.FieldCostCenterCode, field.TypeString, value)
		_node.CostCenterCode = value
	}
	if value, ok := _c.mutation.BudgetItemCode(); ok {
		_spec.SetField(departments.FieldBudgetItemCode, field.TypeString, value)
		_node.BudgetItemCode = value
	}
	if value, ok := _c.mutation.MaxMembers(); ok {
		_spec.SetField(departments.FieldMaxMembers, field.TypeInt, value)
		_node.MaxMembers = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(departments.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(departments.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(departments.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.LionRoleDepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   departments.LionRoleDepartmentsTable,
			Columns: []string{departments.LionRoleDepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledepartments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LionUserDepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   departments.LionUserDepartmentsTable,
			Columns: []string{departments.LionUserDepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdepartments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LionGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   departments.LionGroupsTable,
			Columns: []string{departments.LionGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DepartmentsCreateBulk is the builder for creating many Departments entities in bulk.
type DepartmentsCreateBulk struct {
	config
	err      error
	builders []*DepartmentsCreate
}

// Save creates the Departments entities in the database.
func (_c *DepartmentsCreateBulk) Save(ctx context.Context) ([]*Departments, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Departments, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepartmentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepartmentsCreateBulk) SaveX(ctx context.Context) []*Departments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
