// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/departmentleaders"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// DepartmentLeadersUpdate is the builder for updating DepartmentLeaders entities.
type DepartmentLeadersUpdate struct {
	config
	hooks    []Hook
	mutation *DepartmentLeadersMutation
}

// Where appends a list predicates to the DepartmentLeadersUpdate builder.
func (_u *DepartmentLeadersUpdate) Where(ps ...predicate.DepartmentLeaders) *DepartmentLeadersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepartmentLeadersUpdate) SetUpdatedAt(v time.Time) *DepartmentLeadersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *DepartmentLeadersUpdate) SetDepartmentID(v int) *DepartmentLeadersUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *DepartmentLeadersUpdate) SetNillableDepartmentID(v *int) *DepartmentLeadersUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *DepartmentLeadersUpdate) AddDepartmentID(v int) *DepartmentLeadersUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// SetLeaderType sets the "leader_type" field.
func (_u *DepartmentLeadersUpdate) SetLeaderType(v int) *DepartmentLeadersUpdate {
	_u.mutation.ResetLeaderType()
	_u.mutation.SetLeaderType(v)
	return _u
}

// SetNillableLeaderType sets the "leader_type" field if the given value is not nil.
func (_u *DepartmentLeadersUpdate) SetNillableLeaderType(v *int) *DepartmentLeadersUpdate {
	if v != nil {
		_u.SetLeaderType(*v)
	}
	return _u
}

// AddLeaderType adds value to the "leader_type" field.
func (_u *DepartmentLeadersUpdate) AddLeaderType(v int) *DepartmentLeadersUpdate {
	_u.mutation.AddLeaderType(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DepartmentLeadersUpdate) SetUserID(v int) *DepartmentLeadersUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DepartmentLeadersUpdate) SetNillableUserID(v *int) *DepartmentLeadersUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DepartmentLeadersUpdate) AddUserID(v int) *DepartmentLeadersUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the DepartmentLeadersMutation object of the builder.
func (_u *DepartmentLeadersUpdate) Mutation() *DepartmentLeadersMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepartmentLeadersUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentLeadersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepartmentLeadersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentLeadersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepartmentLeadersUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := departmentleaders.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DepartmentLeadersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(departmentleaders.Table, departmentleaders.Columns, sqlgraph.NewFieldSpec(departmentleaders.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(departmentleaders.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(departmentleaders.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(departmentleaders.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LeaderType(); ok {
		_spec.SetField(departmentleaders.FieldLeaderType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeaderType(); ok {
		_spec.AddField(departmentleaders.FieldLeaderType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(departmentleaders.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(departmentleaders.FieldUserID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{departmentleaders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepartmentLeadersUpdateOne is the builder for updating a single DepartmentLeaders entity.
type DepartmentLeadersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepartmentLeadersMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepartmentLeadersUpdateOne) SetUpdatedAt(v time.Time) *DepartmentLeadersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *DepartmentLeadersUpdateOne) SetDepartmentID(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *DepartmentLeadersUpdateOne) SetNillableDepartmentID(v *int) *DepartmentLeadersUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *DepartmentLeadersUpdateOne) AddDepartmentID(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// SetLeaderType sets the "leader_type" field.
func (_u *DepartmentLeadersUpdateOne) SetLeaderType(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.ResetLeaderType()
	_u.mutation.SetLeaderType(v)
	return _u
}

// SetNillableLeaderType sets the "leader_type" field if the given value is not nil.
func (_u *DepartmentLeadersUpdateOne) SetNillableLeaderType(v *int) *DepartmentLeadersUpdateOne {
	if v != nil {
		_u.SetLeaderType(*v)
	}
	return _u
}

// AddLeaderType adds value to the "leader_type" field.
func (_u *DepartmentLeadersUpdateOne) AddLeaderType(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.AddLeaderType(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DepartmentLeadersUpdateOne) SetUserID(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DepartmentLeadersUpdateOne) SetNillableUserID(v *int) *DepartmentLeadersUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DepartmentLeadersUpdateOne) AddUserID(v int) *DepartmentLeadersUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the DepartmentLeadersMutation object of the builder.
func (_u *DepartmentLeadersUpdateOne) Mutation() *DepartmentLeadersMutation {
	return _u.mutation
}

// Where appends a list predicates to the DepartmentLeadersUpdate builder.
func (_u *DepartmentLeadersUpdateOne) Where(ps ...predicate.DepartmentLeaders) *DepartmentLeadersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepartmentLeadersUpdateOne) Select(field string, fields ...string) *DepartmentLeadersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DepartmentLeaders entity.
func (_u *DepartmentLeadersUpdateOne) Save(ctx context.Context) (*DepartmentLeaders, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepartmentLeadersUpdateOne) SaveX(ctx context.Context) *DepartmentLeaders {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepartmentLeadersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepartmentLeadersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepartmentLeadersUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := departmentleaders.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DepartmentLeadersUpdateOne) sqlSave(ctx context.Context) (_node *DepartmentLeaders, err error) {
	_spec := sqlgraph.NewUpdateSpec(departmentleaders.Table, departmentleaders.Columns, sqlgraph.NewFieldSpec(departmentleaders.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "DepartmentLeaders.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, departmentleaders.FieldID)
		for _, f := range fields {
			if !departmentleaders.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != departmentleaders.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(departmentleaders.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(departmentleaders.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(departmentleaders.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LeaderType(); ok {
		_spec.SetField(departmentleaders.FieldLeaderType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeaderType(); ok {
		_spec.AddField(departmentleaders.FieldLeaderType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(departmentleaders.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(departmentleaders.FieldUserID, field.TypeInt, value)
	}
	_node = &DepartmentLeaders{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{departmentleaders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
