// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/groupusers"
)

// GroupUsersCreate is the builder for creating a GroupUsers entity.
type GroupUsersCreate struct {
	config
	mutation *GroupUsersMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (guc *GroupUsersCreate) SetCreateTime(t time.Time) *GroupUsersCreate {
	guc.mutation.SetCreateTime(t)
	return guc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (guc *GroupUsersCreate) SetNillableCreateTime(t *time.Time) *GroupUsersCreate {
	if t != nil {
		guc.SetCreateTime(*t)
	}
	return guc
}

// SetUpdateTime sets the "update_time" field.
func (guc *GroupUsersCreate) SetUpdateTime(t time.Time) *GroupUsersCreate {
	guc.mutation.SetUpdateTime(t)
	return guc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (guc *GroupUsersCreate) SetNillableUpdateTime(t *time.Time) *GroupUsersCreate {
	if t != nil {
		guc.SetUpdateTime(*t)
	}
	return guc
}

// SetGroupID sets the "group_id" field.
func (guc *GroupUsersCreate) SetGroupID(i int) *GroupUsersCreate {
	guc.mutation.SetGroupID(i)
	return guc
}

// SetUserID sets the "user_id" field.
func (guc *GroupUsersCreate) SetUserID(i int) *GroupUsersCreate {
	guc.mutation.SetUserID(i)
	return guc
}

// Mutation returns the GroupUsersMutation object of the builder.
func (guc *GroupUsersCreate) Mutation() *GroupUsersMutation {
	return guc.mutation
}

// Save creates the GroupUsers in the database.
func (guc *GroupUsersCreate) Save(ctx context.Context) (*GroupUsers, error) {
	guc.defaults()
	return withHooks(ctx, guc.sqlSave, guc.mutation, guc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (guc *GroupUsersCreate) SaveX(ctx context.Context) *GroupUsers {
	v, err := guc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (guc *GroupUsersCreate) Exec(ctx context.Context) error {
	_, err := guc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guc *GroupUsersCreate) ExecX(ctx context.Context) {
	if err := guc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (guc *GroupUsersCreate) defaults() {
	if _, ok := guc.mutation.CreateTime(); !ok {
		v := groupusers.DefaultCreateTime()
		guc.mutation.SetCreateTime(v)
	}
	if _, ok := guc.mutation.UpdateTime(); !ok {
		v := groupusers.DefaultUpdateTime()
		guc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guc *GroupUsersCreate) check() error {
	if _, ok := guc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`lion: missing required field "GroupUsers.create_time"`)}
	}
	if _, ok := guc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`lion: missing required field "GroupUsers.update_time"`)}
	}
	if _, ok := guc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`lion: missing required field "GroupUsers.group_id"`)}
	}
	if v, ok := guc.mutation.GroupID(); ok {
		if err := groupusers.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`lion: validator failed for field "GroupUsers.group_id": %w`, err)}
		}
	}
	if _, ok := guc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`lion: missing required field "GroupUsers.user_id"`)}
	}
	if v, ok := guc.mutation.UserID(); ok {
		if err := groupusers.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`lion: validator failed for field "GroupUsers.user_id": %w`, err)}
		}
	}
	return nil
}

func (guc *GroupUsersCreate) sqlSave(ctx context.Context) (*GroupUsers, error) {
	if err := guc.check(); err != nil {
		return nil, err
	}
	_node, _spec := guc.createSpec()
	if err := sqlgraph.CreateNode(ctx, guc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	guc.mutation.id = &_node.ID
	guc.mutation.done = true
	return _node, nil
}

func (guc *GroupUsersCreate) createSpec() (*GroupUsers, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupUsers{config: guc.config}
		_spec = sqlgraph.NewCreateSpec(groupusers.Table, sqlgraph.NewFieldSpec(groupusers.FieldID, field.TypeInt))
	)
	if value, ok := guc.mutation.CreateTime(); ok {
		_spec.SetField(groupusers.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := guc.mutation.UpdateTime(); ok {
		_spec.SetField(groupusers.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := guc.mutation.GroupID(); ok {
		_spec.SetField(groupusers.FieldGroupID, field.TypeInt, value)
		_node.GroupID = value
	}
	if value, ok := guc.mutation.UserID(); ok {
		_spec.SetField(groupusers.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	return _node, _spec
}

// GroupUsersCreateBulk is the builder for creating many GroupUsers entities in bulk.
type GroupUsersCreateBulk struct {
	config
	err      error
	builders []*GroupUsersCreate
}

// Save creates the GroupUsers entities in the database.
func (gucb *GroupUsersCreateBulk) Save(ctx context.Context) ([]*GroupUsers, error) {
	if gucb.err != nil {
		return nil, gucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gucb.builders))
	nodes := make([]*GroupUsers, len(gucb.builders))
	mutators := make([]Mutator, len(gucb.builders))
	for i := range gucb.builders {
		func(i int, root context.Context) {
			builder := gucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupUsersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gucb *GroupUsersCreateBulk) SaveX(ctx context.Context) []*GroupUsers {
	v, err := gucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gucb *GroupUsersCreateBulk) Exec(ctx context.Context) error {
	_, err := gucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gucb *GroupUsersCreateBulk) ExecX(ctx context.Context) {
	if err := gucb.Exec(ctx); err != nil {
		panic(err)
	}
}
