// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/groupmembers"
	"github.com/grpc-kit/pkg/lion/grouproles"
	"github.com/grpc-kit/pkg/lion/groups"
)

// GroupsCreate is the builder for creating a Groups entity.
type GroupsCreate struct {
	config
	mutation *GroupsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupsCreate) SetCreatedAt(v time.Time) *GroupsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableCreatedAt(v *time.Time) *GroupsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupsCreate) SetUpdatedAt(v time.Time) *GroupsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableUpdatedAt(v *time.Time) *GroupsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *GroupsCreate) SetDeletedAt(v time.Time) *GroupsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableDeletedAt(v *time.Time) *GroupsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GroupsCreate) SetCreatedBy(v int64) *GroupsCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableCreatedBy(v *int64) *GroupsCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *GroupsCreate) SetUpdatedBy(v int64) *GroupsCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableUpdatedBy(v *int64) *GroupsCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *GroupsCreate) SetCode(v string) *GroupsCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *GroupsCreate) SetDisplayName(v string) *GroupsCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetGroupType sets the "group_type" field.
func (_c *GroupsCreate) SetGroupType(v int) *GroupsCreate {
	_c.mutation.SetGroupType(v)
	return _c
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableGroupType(v *int) *GroupsCreate {
	if v != nil {
		_c.SetGroupType(*v)
	}
	return _c
}

// SetGroupStatus sets the "group_status" field.
func (_c *GroupsCreate) SetGroupStatus(v int) *GroupsCreate {
	_c.mutation.SetGroupStatus(v)
	return _c
}

// SetNillableGroupStatus sets the "group_status" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableGroupStatus(v *int) *GroupsCreate {
	if v != nil {
		_c.SetGroupStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *GroupsCreate) SetSortOrder(v int) *GroupsCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableSortOrder(v *int) *GroupsCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *GroupsCreate) SetParentID(v int) *GroupsCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableParentID(v *int) *GroupsCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetMaxMembers sets the "max_members" field.
func (_c *GroupsCreate) SetMaxMembers(v int) *GroupsCreate {
	_c.mutation.SetMaxMembers(v)
	return _c
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableMaxMembers(v *int) *GroupsCreate {
	if v != nil {
		_c.SetMaxMembers(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *GroupsCreate) SetMetadata(v map[string]string) *GroupsCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetRefID sets the "ref_id" field.
func (_c *GroupsCreate) SetRefID(v int) *GroupsCreate {
	_c.mutation.SetRefID(v)
	return _c
}

// SetNillableRefID sets the "ref_id" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableRefID(v *int) *GroupsCreate {
	if v != nil {
		_c.SetRefID(*v)
	}
	return _c
}

// SetRefExpr sets the "ref_expr" field.
func (_c *GroupsCreate) SetRefExpr(v string) *GroupsCreate {
	_c.mutation.SetRefExpr(v)
	return _c
}

// SetNillableRefExpr sets the "ref_expr" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableRefExpr(v *string) *GroupsCreate {
	if v != nil {
		_c.SetRefExpr(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *GroupsCreate) SetVisibility(v int) *GroupsCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableVisibility(v *int) *GroupsCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *GroupsCreate) SetDescription(v string) *GroupsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GroupsCreate) SetNillableDescription(v *string) *GroupsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// AddLionGroupIDs adds the "lion_groups" edge to the GroupRoles entity by IDs.
func (_c *GroupsCreate) AddLionGroupIDs(ids ...int) *GroupsCreate {
	_c.mutation.AddLionGroupIDs(ids...)
	return _c
}

// AddLionGroups adds the "lion_groups" edges to the GroupRoles entity.
func (_c *GroupsCreate) AddLionGroups(v ...*GroupRoles) *GroupsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLionGroupIDs(ids...)
}

// AddLionGroupMemberIDs adds the "lion_group_members" edge to the GroupMembers entity by IDs.
func (_c *GroupsCreate) AddLionGroupMemberIDs(ids ...int) *GroupsCreate {
	_c.mutation.AddLionGroupMemberIDs(ids...)
	return _c
}

// AddLionGroupMembers adds the "lion_group_members" edges to the GroupMembers entity.
func (_c *GroupsCreate) AddLionGroupMembers(v ...*GroupMembers) *GroupsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLionGroupMemberIDs(ids...)
}

// Mutation returns the GroupsMutation object of the builder.
func (_c *GroupsCreate) Mutation() *GroupsMutation {
	return _c.mutation
}

// Save creates the Groups in the database.
func (_c *GroupsCreate) Save(ctx context.Context) (*Groups, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupsCreate) SaveX(ctx context.Context) *Groups {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groups.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groups.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := groups.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		v := groups.DefaultUpdatedBy
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.GroupType(); !ok {
		v := groups.DefaultGroupType
		_c.mutation.SetGroupType(v)
	}
	if _, ok := _c.mutation.GroupStatus(); !ok {
		v := groups.DefaultGroupStatus
		_c.mutation.SetGroupStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := groups.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := groups.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		v := groups.DefaultMaxMembers
		_c.mutation.SetMaxMembers(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := groups.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.RefID(); !ok {
		v := groups.DefaultRefID
		_c.mutation.SetRefID(v)
	}
	if _, ok := _c.mutation.RefExpr(); !ok {
		v := groups.DefaultRefExpr
		_c.mutation.SetRefExpr(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := groups.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := groups.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "Groups.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "Groups.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`lion: missing required field "Groups.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := groups.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`lion: validator failed for field "Groups.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`lion: missing required field "Groups.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := groups.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`lion: validator failed for field "Groups.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupType(); !ok {
		return &ValidationError{Name: "group_type", err: errors.New(`lion: missing required field "Groups.group_type"`)}
	}
	if _, ok := _c.mutation.GroupStatus(); !ok {
		return &ValidationError{Name: "group_status", err: errors.New(`lion: missing required field "Groups.group_status"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`lion: missing required field "Groups.sort_order"`)}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`lion: missing required field "Groups.parent_id"`)}
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		return &ValidationError{Name: "max_members", err: errors.New(`lion: missing required field "Groups.max_members"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`lion: missing required field "Groups.metadata"`)}
	}
	if _, ok := _c.mutation.RefID(); !ok {
		return &ValidationError{Name: "ref_id", err: errors.New(`lion: missing required field "Groups.ref_id"`)}
	}
	if _, ok := _c.mutation.RefExpr(); !ok {
		return &ValidationError{Name: "ref_expr", err: errors.New(`lion: missing required field "Groups.ref_expr"`)}
	}
	if v, ok := _c.mutation.RefExpr(); ok {
		if err := groups.RefExprValidator(v); err != nil {
			return &ValidationError{Name: "ref_expr", err: fmt.Errorf(`lion: validator failed for field "Groups.ref_expr": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`lion: missing required field "Groups.visibility"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`lion: missing required field "Groups.description"`)}
	}
	return nil
}

func (_c *GroupsCreate) sqlSave(ctx context.Context) (*Groups, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupsCreate) createSpec() (*Groups, *sqlgraph.CreateSpec) {
	var (
		_node = &Groups{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groups.Table, sqlgraph.NewFieldSpec(groups.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groups.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groups.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(groups.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(groups.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(groups.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(groups.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(groups.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.GroupType(); ok {
		_spec.SetField(groups.FieldGroupType, field.TypeInt, value)
		_node.GroupType = value
	}
	if value, ok := _c.mutation.GroupStatus(); ok {
		_spec.SetField(groups.FieldGroupStatus, field.TypeInt, value)
		_node.GroupStatus = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(groups.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(groups.FieldParentID, field.TypeInt, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.MaxMembers(); ok {
		_spec.SetField(groups.FieldMaxMembers, field.TypeInt, value)
		_node.MaxMembers = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(groups.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.RefID(); ok {
		_spec.SetField(groups.FieldRefID, field.TypeInt, value)
		_node.RefID = value
	}
	if value, ok := _c.mutation.RefExpr(); ok {
		_spec.SetField(groups.FieldRefExpr, field.TypeString, value)
		_node.RefExpr = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(groups.FieldVisibility, field.TypeInt, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(groups.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.LionGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groups.LionGroupsTable,
			Columns: []string{groups.LionGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grouproles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LionGroupMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groups.LionGroupMembersTable,
			Columns: []string{groups.LionGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupsCreateBulk is the builder for creating many Groups entities in bulk.
type GroupsCreateBulk struct {
	config
	err      error
	builders []*GroupsCreate
}

// Save creates the Groups entities in the database.
func (_c *GroupsCreateBulk) Save(ctx context.Context) ([]*Groups, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Groups, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupsCreateBulk) SaveX(ctx context.Context) []*Groups {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
