// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/oauth2codes"
)

// OAuth2CodesCreate is the builder for creating a OAuth2Codes entity.
type OAuth2CodesCreate struct {
	config
	mutation *OAuth2CodesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuth2CodesCreate) SetCreatedAt(v time.Time) *OAuth2CodesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableCreatedAt(v *time.Time) *OAuth2CodesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuth2CodesCreate) SetUpdatedAt(v time.Time) *OAuth2CodesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableUpdatedAt(v *time.Time) *OAuth2CodesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *OAuth2CodesCreate) SetCodeHash(v string) *OAuth2CodesCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuth2CodesCreate) SetClientID(v string) *OAuth2CodesCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuth2CodesCreate) SetRedirectURI(v string) *OAuth2CodesCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuth2CodesCreate) SetUserID(v int) *OAuth2CodesCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableUserID(v *int) *OAuth2CodesCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *OAuth2CodesCreate) SetUsername(v string) *OAuth2CodesCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableUsername(v *string) *OAuth2CodesCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuth2CodesCreate) SetScopes(v []string) *OAuth2CodesCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OAuth2CodesCreate) SetState(v string) *OAuth2CodesCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableState(v *string) *OAuth2CodesCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *OAuth2CodesCreate) SetNonce(v string) *OAuth2CodesCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableNonce(v *string) *OAuth2CodesCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuth2CodesCreate) SetCodeChallenge(v string) *OAuth2CodesCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableCodeChallenge(v *string) *OAuth2CodesCreate {
	if v != nil {
		_c.SetCodeChallenge(*v)
	}
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OAuth2CodesCreate) SetCodeChallengeMethod(v string) *OAuth2CodesCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableCodeChallengeMethod(v *string) *OAuth2CodesCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuth2CodesCreate) SetExpiresAt(v time.Time) *OAuth2CodesCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OAuth2CodesCreate) SetConsumedAt(v time.Time) *OAuth2CodesCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OAuth2CodesCreate) SetNillableConsumedAt(v *time.Time) *OAuth2CodesCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// Mutation returns the OAuth2CodesMutation object of the builder.
func (_c *OAuth2CodesCreate) Mutation() *OAuth2CodesMutation {
	return _c.mutation
}

// Save creates the OAuth2Codes in the database.
func (_c *OAuth2CodesCreate) Save(ctx context.Context) (*OAuth2Codes, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuth2CodesCreate) SaveX(ctx context.Context) *OAuth2Codes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuth2CodesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuth2CodesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuth2CodesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauth2codes.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauth2codes.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UserID(); !ok {
		v := oauth2codes.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := oauth2codes.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := oauth2codes.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		v := oauth2codes.DefaultNonce
		_c.mutation.SetNonce(v)
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		v := oauth2codes.DefaultCodeChallenge
		_c.mutation.SetCodeChallenge(v)
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := oauth2codes.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuth2CodesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "OAuth2Codes.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "OAuth2Codes.updated_at"`)}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`lion: missing required field "OAuth2Codes.code_hash"`)}
	}
	if v, ok := _c.mutation.CodeHash(); ok {
		if err := oauth2codes.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.code_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`lion: missing required field "OAuth2Codes.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauth2codes.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`lion: missing required field "OAuth2Codes.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauth2codes.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`lion: missing required field "OAuth2Codes.user_id"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`lion: missing required field "OAuth2Codes.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := oauth2codes.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`lion: missing required field "OAuth2Codes.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := oauth2codes.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`lion: missing required field "OAuth2Codes.nonce"`)}
	}
	if v, ok := _c.mutation.Nonce(); ok {
		if err := oauth2codes.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`lion: missing required field "OAuth2Codes.code_challenge"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauth2codes.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.code_challenge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`lion: missing required field "OAuth2Codes.code_challenge_method"`)}
	}
	if v, ok := _c.mutation.CodeChallengeMethod(); ok {
		if err := oauth2codes.CodeChallengeMethodValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge_method", err: fmt.Errorf(`lion: validator failed for field "OAuth2Codes.code_challenge_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`lion: missing required field "OAuth2Codes.expires_at"`)}
	}
	return nil
}

func (_c *OAuth2CodesCreate) sqlSave(ctx context.Context) (*OAuth2Codes, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuth2CodesCreate) createSpec() (*OAuth2Codes, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuth2Codes{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauth2codes.Table, sqlgraph.NewFieldSpec(oauth2codes.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauth2codes.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauth2codes.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(oauth2codes.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauth2codes.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauth2codes.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauth2codes.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(oauth2codes.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauth2codes.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(oauth2codes.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(oauth2codes.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauth2codes.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauth2codes.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauth2codes.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oauth2codes.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OAuth2CodesCreateBulk is the builder for creating many OAuth2Codes entities in bulk.
type OAuth2CodesCreateBulk struct {
	config
	err      error
	builders []*OAuth2CodesCreate
}

// Save creates the OAuth2Codes entities in the database.
func (_c *OAuth2CodesCreateBulk) Save(ctx context.Context) ([]*OAuth2Codes, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuth2Codes, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuth2CodesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuth2CodesCreateBulk) SaveX(ctx context.Context) []*OAuth2Codes {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuth2CodesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuth2CodesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
