// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/permissionresources"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// PermissionResourcesDelete is the builder for deleting a PermissionResources entity.
type PermissionResourcesDelete struct {
	config
	hooks    []Hook
	mutation *PermissionResourcesMutation
}

// Where appends a list predicates to the PermissionResourcesDelete builder.
func (_d *PermissionResourcesDelete) Where(ps ...predicate.PermissionResources) *PermissionResourcesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PermissionResourcesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionResourcesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PermissionResourcesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissionresources.Table, sqlgraph.NewFieldSpec(permissionresources.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PermissionResourcesDeleteOne is the builder for deleting a single PermissionResources entity.
type PermissionResourcesDeleteOne struct {
	_d *PermissionResourcesDelete
}

// Where appends a list predicates to the PermissionResourcesDelete builder.
func (_d *PermissionResourcesDeleteOne) Where(ps ...predicate.PermissionResources) *PermissionResourcesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PermissionResourcesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissionresources.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionResourcesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
