// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/policies"
	"github.com/grpc-kit/pkg/lion/policystatements"
	"github.com/grpc-kit/pkg/lion/predicate"
)

// PolicyStatementsUpdate is the builder for updating PolicyStatements entities.
type PolicyStatementsUpdate struct {
	config
	hooks    []Hook
	mutation *PolicyStatementsMutation
}

// Where appends a list predicates to the PolicyStatementsUpdate builder.
func (_u *PolicyStatementsUpdate) Where(ps ...predicate.PolicyStatements) *PolicyStatementsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PolicyStatementsUpdate) SetUpdatedAt(v time.Time) *PolicyStatementsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PolicyStatementsUpdate) SetCreatedBy(v int64) *PolicyStatementsUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableCreatedBy(v *int64) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PolicyStatementsUpdate) AddCreatedBy(v int64) *PolicyStatementsUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PolicyStatementsUpdate) ClearCreatedBy() *PolicyStatementsUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PolicyStatementsUpdate) SetUpdatedBy(v int64) *PolicyStatementsUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableUpdatedBy(v *int64) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PolicyStatementsUpdate) AddUpdatedBy(v int64) *PolicyStatementsUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PolicyStatementsUpdate) ClearUpdatedBy() *PolicyStatementsUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyStatementsUpdate) SetPolicyID(v int) *PolicyStatementsUpdate {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillablePolicyID(v *int) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetSid sets the "sid" field.
func (_u *PolicyStatementsUpdate) SetSid(v string) *PolicyStatementsUpdate {
	_u.mutation.SetSid(v)
	return _u
}

// SetNillableSid sets the "sid" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableSid(v *string) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetSid(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *PolicyStatementsUpdate) SetEffect(v int) *PolicyStatementsUpdate {
	_u.mutation.ResetEffect()
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableEffect(v *int) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// AddEffect adds value to the "effect" field.
func (_u *PolicyStatementsUpdate) AddEffect(v int) *PolicyStatementsUpdate {
	_u.mutation.AddEffect(v)
	return _u
}

// SetActionSelector sets the "action_selector" field.
func (_u *PolicyStatementsUpdate) SetActionSelector(v string) *PolicyStatementsUpdate {
	_u.mutation.SetActionSelector(v)
	return _u
}

// SetNillableActionSelector sets the "action_selector" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableActionSelector(v *string) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetActionSelector(*v)
	}
	return _u
}

// SetResourceSelector sets the "resource_selector" field.
func (_u *PolicyStatementsUpdate) SetResourceSelector(v string) *PolicyStatementsUpdate {
	_u.mutation.SetResourceSelector(v)
	return _u
}

// SetNillableResourceSelector sets the "resource_selector" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableResourceSelector(v *string) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetResourceSelector(*v)
	}
	return _u
}

// SetConditionJSON sets the "condition_json" field.
func (_u *PolicyStatementsUpdate) SetConditionJSON(v string) *PolicyStatementsUpdate {
	_u.mutation.SetConditionJSON(v)
	return _u
}

// SetNillableConditionJSON sets the "condition_json" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableConditionJSON(v *string) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetConditionJSON(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PolicyStatementsUpdate) SetPriority(v int) *PolicyStatementsUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillablePriority(v *int) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PolicyStatementsUpdate) AddPriority(v int) *PolicyStatementsUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *PolicyStatementsUpdate) SetDescription(v string) *PolicyStatementsUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PolicyStatementsUpdate) SetNillableDescription(v *string) *PolicyStatementsUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLionPoliciesID sets the "lion_policies" edge to the Policies entity by ID.
func (_u *PolicyStatementsUpdate) SetLionPoliciesID(id int) *PolicyStatementsUpdate {
	_u.mutation.SetLionPoliciesID(id)
	return _u
}

// SetLionPolicies sets the "lion_policies" edge to the Policies entity.
func (_u *PolicyStatementsUpdate) SetLionPolicies(v *Policies) *PolicyStatementsUpdate {
	return _u.SetLionPoliciesID(v.ID)
}

// Mutation returns the PolicyStatementsMutation object of the builder.
func (_u *PolicyStatementsUpdate) Mutation() *PolicyStatementsMutation {
	return _u.mutation
}

// ClearLionPolicies clears the "lion_policies" edge to the Policies entity.
func (_u *PolicyStatementsUpdate) ClearLionPolicies() *PolicyStatementsUpdate {
	_u.mutation.ClearLionPolicies()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicyStatementsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyStatementsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicyStatementsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyStatementsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PolicyStatementsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := policystatements.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyStatementsUpdate) check() error {
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := policystatements.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`lion: validator failed for field "PolicyStatements.policy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sid(); ok {
		if err := policystatements.SidValidator(v); err != nil {
			return &ValidationError{Name: "sid", err: fmt.Errorf(`lion: validator failed for field "PolicyStatements.sid": %w`, err)}
		}
	}
	if _u.mutation.LionPoliciesCleared() && len(_u.mutation.LionPoliciesIDs()) > 0 {
		return errors.New(`lion: clearing a required unique edge "PolicyStatements.lion_policies"`)
	}
	return nil
}

func (_u *PolicyStatementsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policystatements.Table, policystatements.Columns, sqlgraph.NewFieldSpec(policystatements.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(policystatements.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(policystatements.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(policystatements.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(policystatements.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(policystatements.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(policystatements.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(policystatements.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Sid(); ok {
		_spec.SetField(policystatements.FieldSid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(policystatements.FieldEffect, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEffect(); ok {
		_spec.AddField(policystatements.FieldEffect, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionSelector(); ok {
		_spec.SetField(policystatements.FieldActionSelector, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceSelector(); ok {
		_spec.SetField(policystatements.FieldResourceSelector, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionJSON(); ok {
		_spec.SetField(policystatements.FieldConditionJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(policystatements.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(policystatements.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(policystatements.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.LionPoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policystatements.LionPoliciesTable,
			Columns: []string{policystatements.LionPoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policies.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionPoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policystatements.LionPoliciesTable,
			Columns: []string{policystatements.LionPoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policies.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policystatements.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicyStatementsUpdateOne is the builder for updating a single PolicyStatements entity.
type PolicyStatementsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicyStatementsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PolicyStatementsUpdateOne) SetUpdatedAt(v time.Time) *PolicyStatementsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PolicyStatementsUpdateOne) SetCreatedBy(v int64) *PolicyStatementsUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableCreatedBy(v *int64) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *PolicyStatementsUpdateOne) AddCreatedBy(v int64) *PolicyStatementsUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PolicyStatementsUpdateOne) ClearCreatedBy() *PolicyStatementsUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PolicyStatementsUpdateOne) SetUpdatedBy(v int64) *PolicyStatementsUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableUpdatedBy(v *int64) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PolicyStatementsUpdateOne) AddUpdatedBy(v int64) *PolicyStatementsUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PolicyStatementsUpdateOne) ClearUpdatedBy() *PolicyStatementsUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetPolicyID sets the "policy_id" field.
func (_u *PolicyStatementsUpdateOne) SetPolicyID(v int) *PolicyStatementsUpdateOne {
	_u.mutation.SetPolicyID(v)
	return _u
}

// SetNillablePolicyID sets the "policy_id" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillablePolicyID(v *int) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetPolicyID(*v)
	}
	return _u
}

// SetSid sets the "sid" field.
func (_u *PolicyStatementsUpdateOne) SetSid(v string) *PolicyStatementsUpdateOne {
	_u.mutation.SetSid(v)
	return _u
}

// SetNillableSid sets the "sid" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableSid(v *string) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetSid(*v)
	}
	return _u
}

// SetEffect sets the "effect" field.
func (_u *PolicyStatementsUpdateOne) SetEffect(v int) *PolicyStatementsUpdateOne {
	_u.mutation.ResetEffect()
	_u.mutation.SetEffect(v)
	return _u
}

// SetNillableEffect sets the "effect" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableEffect(v *int) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetEffect(*v)
	}
	return _u
}

// AddEffect adds value to the "effect" field.
func (_u *PolicyStatementsUpdateOne) AddEffect(v int) *PolicyStatementsUpdateOne {
	_u.mutation.AddEffect(v)
	return _u
}

// SetActionSelector sets the "action_selector" field.
func (_u *PolicyStatementsUpdateOne) SetActionSelector(v string) *PolicyStatementsUpdateOne {
	_u.mutation.SetActionSelector(v)
	return _u
}

// SetNillableActionSelector sets the "action_selector" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableActionSelector(v *string) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetActionSelector(*v)
	}
	return _u
}

// SetResourceSelector sets the "resource_selector" field.
func (_u *PolicyStatementsUpdateOne) SetResourceSelector(v string) *PolicyStatementsUpdateOne {
	_u.mutation.SetResourceSelector(v)
	return _u
}

// SetNillableResourceSelector sets the "resource_selector" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableResourceSelector(v *string) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetResourceSelector(*v)
	}
	return _u
}

// SetConditionJSON sets the "condition_json" field.
func (_u *PolicyStatementsUpdateOne) SetConditionJSON(v string) *PolicyStatementsUpdateOne {
	_u.mutation.SetConditionJSON(v)
	return _u
}

// SetNillableConditionJSON sets the "condition_json" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableConditionJSON(v *string) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetConditionJSON(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PolicyStatementsUpdateOne) SetPriority(v int) *PolicyStatementsUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillablePriority(v *int) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PolicyStatementsUpdateOne) AddPriority(v int) *PolicyStatementsUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *PolicyStatementsUpdateOne) SetDescription(v string) *PolicyStatementsUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PolicyStatementsUpdateOne) SetNillableDescription(v *string) *PolicyStatementsUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLionPoliciesID sets the "lion_policies" edge to the Policies entity by ID.
func (_u *PolicyStatementsUpdateOne) SetLionPoliciesID(id int) *PolicyStatementsUpdateOne {
	_u.mutation.SetLionPoliciesID(id)
	return _u
}

// SetLionPolicies sets the "lion_policies" edge to the Policies entity.
func (_u *PolicyStatementsUpdateOne) SetLionPolicies(v *Policies) *PolicyStatementsUpdateOne {
	return _u.SetLionPoliciesID(v.ID)
}

// Mutation returns the PolicyStatementsMutation object of the builder.
func (_u *PolicyStatementsUpdateOne) Mutation() *PolicyStatementsMutation {
	return _u.mutation
}

// ClearLionPolicies clears the "lion_policies" edge to the Policies entity.
func (_u *PolicyStatementsUpdateOne) ClearLionPolicies() *PolicyStatementsUpdateOne {
	_u.mutation.ClearLionPolicies()
	return _u
}

// Where appends a list predicates to the PolicyStatementsUpdate builder.
func (_u *PolicyStatementsUpdateOne) Where(ps ...predicate.PolicyStatements) *PolicyStatementsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicyStatementsUpdateOne) Select(field string, fields ...string) *PolicyStatementsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PolicyStatements entity.
func (_u *PolicyStatementsUpdateOne) Save(ctx context.Context) (*PolicyStatements, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyStatementsUpdateOne) SaveX(ctx context.Context) *PolicyStatements {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicyStatementsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyStatementsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PolicyStatementsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := policystatements.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyStatementsUpdateOne) check() error {
	if v, ok := _u.mutation.PolicyID(); ok {
		if err := policystatements.PolicyIDValidator(v); err != nil {
			return &ValidationError{Name: "policy_id", err: fmt.Errorf(`lion: validator failed for field "PolicyStatements.policy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sid(); ok {
		if err := policystatements.SidValidator(v); err != nil {
			return &ValidationError{Name: "sid", err: fmt.Errorf(`lion: validator failed for field "PolicyStatements.sid": %w`, err)}
		}
	}
	if _u.mutation.LionPoliciesCleared() && len(_u.mutation.LionPoliciesIDs()) > 0 {
		return errors.New(`lion: clearing a required unique edge "PolicyStatements.lion_policies"`)
	}
	return nil
}

func (_u *PolicyStatementsUpdateOne) sqlSave(ctx context.Context) (_node *PolicyStatements, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policystatements.Table, policystatements.Columns, sqlgraph.NewFieldSpec(policystatements.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "PolicyStatements.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policystatements.FieldID)
		for _, f := range fields {
			if !policystatements.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != policystatements.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(policystatements.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(policystatements.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(policystatements.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(policystatements.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(policystatements.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(policystatements.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(policystatements.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Sid(); ok {
		_spec.SetField(policystatements.FieldSid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Effect(); ok {
		_spec.SetField(policystatements.FieldEffect, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEffect(); ok {
		_spec.AddField(policystatements.FieldEffect, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActionSelector(); ok {
		_spec.SetField(policystatements.FieldActionSelector, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceSelector(); ok {
		_spec.SetField(policystatements.FieldResourceSelector, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConditionJSON(); ok {
		_spec.SetField(policystatements.FieldConditionJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(policystatements.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(policystatements.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(policystatements.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.LionPoliciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policystatements.LionPoliciesTable,
			Columns: []string{policystatements.LionPoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policies.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionPoliciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policystatements.LionPoliciesTable,
			Columns: []string{policystatements.LionPoliciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policies.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PolicyStatements{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policystatements.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
