// Code generated by ent, DO NOT EDIT.

package lion

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/principalroles"
	"github.com/grpc-kit/pkg/lion/roles"
)

// PrincipalRoles is the model entity for the PrincipalRoles schema.
type PrincipalRoles struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// 主体类型：0-未指定，1-用户，2-群组，3-部门
	PrincipalType int `json:"principal_type,omitempty"`
	// 主体 ID，与 principal_type 配合使用
	PrincipalID int `json:"principal_id,omitempty"`
	// 角色 ID，关联 lion_roles
	RoleID int `json:"role_id,omitempty"`
	// 绑定状态：1-生效，2-禁用
	BindingStatus int `json:"binding_status,omitempty"`
	// 绑定有效期，空表示永久有效
	ExpiredAt time.Time `json:"expired_at,omitempty"`
	// 元数据，用于存储来源等扩展属性
	Metadata map[string]string `json:"metadata,omitempty"`
	// 绑定关系描述
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PrincipalRolesQuery when eager-loading is set.
	Edges        PrincipalRolesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PrincipalRolesEdges holds the relations/edges for other nodes in the graph.
type PrincipalRolesEdges struct {
	// LionRoles holds the value of the lion_roles edge.
	LionRoles *Roles `json:"lion_roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LionRolesOrErr returns the LionRoles value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PrincipalRolesEdges) LionRolesOrErr() (*Roles, error) {
	if e.LionRoles != nil {
		return e.LionRoles, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: roles.Label}
	}
	return nil, &NotLoadedError{edge: "lion_roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PrincipalRoles) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case principalroles.FieldMetadata:
			values[i] = new([]byte)
		case principalroles.FieldID, principalroles.FieldCreatedBy, principalroles.FieldUpdatedBy, principalroles.FieldPrincipalType, principalroles.FieldPrincipalID, principalroles.FieldRoleID, principalroles.FieldBindingStatus:
			values[i] = new(sql.NullInt64)
		case principalroles.FieldDescription:
			values[i] = new(sql.NullString)
		case principalroles.FieldCreatedAt, principalroles.FieldUpdatedAt, principalroles.FieldExpiredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PrincipalRoles fields.
func (_m *PrincipalRoles) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case principalroles.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case principalroles.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case principalroles.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case principalroles.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case principalroles.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case principalroles.FieldPrincipalType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field principal_type", values[i])
			} else if value.Valid {
				_m.PrincipalType = int(value.Int64)
			}
		case principalroles.FieldPrincipalID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field principal_id", values[i])
			} else if value.Valid {
				_m.PrincipalID = int(value.Int64)
			}
		case principalroles.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = int(value.Int64)
			}
		case principalroles.FieldBindingStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field binding_status", values[i])
			} else if value.Valid {
				_m.BindingStatus = int(value.Int64)
			}
		case principalroles.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				_m.ExpiredAt = value.Time
			}
		case principalroles.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case principalroles.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PrincipalRoles.
// This includes values selected through modifiers, order, etc.
func (_m *PrincipalRoles) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLionRoles queries the "lion_roles" edge of the PrincipalRoles entity.
func (_m *PrincipalRoles) QueryLionRoles() *RolesQuery {
	return NewPrincipalRolesClient(_m.config).QueryLionRoles(_m)
}

// Update returns a builder for updating this PrincipalRoles.
// Note that you need to call PrincipalRoles.Unwrap() before calling this method if this PrincipalRoles
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PrincipalRoles) Update() *PrincipalRolesUpdateOne {
	return NewPrincipalRolesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PrincipalRoles entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PrincipalRoles) Unwrap() *PrincipalRoles {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: PrincipalRoles is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PrincipalRoles) String() string {
	var builder strings.Builder
	builder.WriteString("PrincipalRoles(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("principal_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalType))
	builder.WriteString(", ")
	builder.WriteString("principal_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("binding_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.BindingStatus))
	builder.WriteString(", ")
	builder.WriteString("expired_at=")
	builder.WriteString(_m.ExpiredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// PrincipalRolesSlice is a parsable slice of PrincipalRoles.
type PrincipalRolesSlice []*PrincipalRoles
