// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/menus"
	"github.com/grpc-kit/pkg/lion/predicate"
	"github.com/grpc-kit/pkg/lion/resources"
	"github.com/grpc-kit/pkg/lion/resourcescopes"
	"github.com/grpc-kit/pkg/lion/resourcetypes"
)

// ResourcesUpdate is the builder for updating Resources entities.
type ResourcesUpdate struct {
	config
	hooks    []Hook
	mutation *ResourcesMutation
}

// Where appends a list predicates to the ResourcesUpdate builder.
func (_u *ResourcesUpdate) Where(ps ...predicate.Resources) *ResourcesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourcesUpdate) SetUpdatedAt(v time.Time) *ResourcesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourcesUpdate) SetDeletedAt(v time.Time) *ResourcesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableDeletedAt(v *time.Time) *ResourcesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourcesUpdate) ClearDeletedAt() *ResourcesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ResourcesUpdate) SetCreatedBy(v int64) *ResourcesUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableCreatedBy(v *int64) *ResourcesUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ResourcesUpdate) AddCreatedBy(v int64) *ResourcesUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ResourcesUpdate) ClearCreatedBy() *ResourcesUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ResourcesUpdate) SetUpdatedBy(v int64) *ResourcesUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableUpdatedBy(v *int64) *ResourcesUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ResourcesUpdate) AddUpdatedBy(v int64) *ResourcesUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ResourcesUpdate) ClearUpdatedBy() *ResourcesUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourcesUpdate) SetParentID(v int64) *ResourcesUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableParentID(v *int64) *ResourcesUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ResourcesUpdate) AddParentID(v int64) *ResourcesUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetResourceTypeID sets the "resource_type_id" field.
func (_u *ResourcesUpdate) SetResourceTypeID(v int) *ResourcesUpdate {
	_u.mutation.SetResourceTypeID(v)
	return _u
}

// SetNillableResourceTypeID sets the "resource_type_id" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourceTypeID(v *int) *ResourcesUpdate {
	if v != nil {
		_u.SetResourceTypeID(*v)
	}
	return _u
}

// SetResourceTypeCode sets the "resource_type_code" field.
func (_u *ResourcesUpdate) SetResourceTypeCode(v string) *ResourcesUpdate {
	_u.mutation.SetResourceTypeCode(v)
	return _u
}

// SetNillableResourceTypeCode sets the "resource_type_code" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourceTypeCode(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetResourceTypeCode(*v)
	}
	return _u
}

// SetServiceCode sets the "service_code" field.
func (_u *ResourcesUpdate) SetServiceCode(v string) *ResourcesUpdate {
	_u.mutation.SetServiceCode(v)
	return _u
}

// SetNillableServiceCode sets the "service_code" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableServiceCode(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetServiceCode(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ResourcesUpdate) SetTenantID(v string) *ResourcesUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableTenantID(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ResourcesUpdate) SetRegion(v string) *ResourcesUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableRegion(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetResourcePath sets the "resource_path" field.
func (_u *ResourcesUpdate) SetResourcePath(v string) *ResourcesUpdate {
	_u.mutation.SetResourcePath(v)
	return _u
}

// SetNillableResourcePath sets the "resource_path" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourcePath(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetResourcePath(*v)
	}
	return _u
}

// SetGrn sets the "grn" field.
func (_u *ResourcesUpdate) SetGrn(v string) *ResourcesUpdate {
	_u.mutation.SetGrn(v)
	return _u
}

// SetNillableGrn sets the "grn" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableGrn(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetGrn(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ResourcesUpdate) SetCode(v string) *ResourcesUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableCode(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourcesUpdate) SetName(v string) *ResourcesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableName(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ResourcesUpdate) SetDisplayName(v string) *ResourcesUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableDisplayName(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourcesUpdate) SetResourceType(v int) *ResourcesUpdate {
	_u.mutation.ResetResourceType()
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourceType(v *int) *ResourcesUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// AddResourceType adds value to the "resource_type" field.
func (_u *ResourcesUpdate) AddResourceType(v int) *ResourcesUpdate {
	_u.mutation.AddResourceType(v)
	return _u
}

// SetResourceStatus sets the "resource_status" field.
func (_u *ResourcesUpdate) SetResourceStatus(v int) *ResourcesUpdate {
	_u.mutation.ResetResourceStatus()
	_u.mutation.SetResourceStatus(v)
	return _u
}

// SetNillableResourceStatus sets the "resource_status" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourceStatus(v *int) *ResourcesUpdate {
	if v != nil {
		_u.SetResourceStatus(*v)
	}
	return _u
}

// AddResourceStatus adds value to the "resource_status" field.
func (_u *ResourcesUpdate) AddResourceStatus(v int) *ResourcesUpdate {
	_u.mutation.AddResourceStatus(v)
	return _u
}

// SetResourceStatusCode sets the "resource_status_code" field.
func (_u *ResourcesUpdate) SetResourceStatusCode(v string) *ResourcesUpdate {
	_u.mutation.SetResourceStatusCode(v)
	return _u
}

// SetNillableResourceStatusCode sets the "resource_status_code" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableResourceStatusCode(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetResourceStatusCode(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ResourcesUpdate) SetVisibility(v int) *ResourcesUpdate {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableVisibility(v *int) *ResourcesUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *ResourcesUpdate) AddVisibility(v int) *ResourcesUpdate {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ResourcesUpdate) SetSortOrder(v int) *ResourcesUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableSortOrder(v *int) *ResourcesUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ResourcesUpdate) AddSortOrder(v int) *ResourcesUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetLocator sets the "locator" field.
func (_u *ResourcesUpdate) SetLocator(v string) *ResourcesUpdate {
	_u.mutation.SetLocator(v)
	return _u
}

// SetNillableLocator sets the "locator" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableLocator(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetLocator(*v)
	}
	return _u
}

// SetVisual sets the "visual" field.
func (_u *ResourcesUpdate) SetVisual(v string) *ResourcesUpdate {
	_u.mutation.SetVisual(v)
	return _u
}

// SetNillableVisual sets the "visual" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableVisual(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetVisual(*v)
	}
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *ResourcesUpdate) SetManifest(v string) *ResourcesUpdate {
	_u.mutation.SetManifest(v)
	return _u
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableManifest(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetManifest(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourcesUpdate) SetDescription(v string) *ResourcesUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableDescription(v *string) *ResourcesUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProtected sets the "protected" field.
func (_u *ResourcesUpdate) SetProtected(v bool) *ResourcesUpdate {
	_u.mutation.SetProtected(v)
	return _u
}

// SetNillableProtected sets the "protected" field if the given value is not nil.
func (_u *ResourcesUpdate) SetNillableProtected(v *bool) *ResourcesUpdate {
	if v != nil {
		_u.SetProtected(*v)
	}
	return _u
}

// SetLionResourceTypesID sets the "lion_resource_types" edge to the ResourceTypes entity by ID.
func (_u *ResourcesUpdate) SetLionResourceTypesID(id int) *ResourcesUpdate {
	_u.mutation.SetLionResourceTypesID(id)
	return _u
}

// SetLionResourceTypes sets the "lion_resource_types" edge to the ResourceTypes entity.
func (_u *ResourcesUpdate) SetLionResourceTypes(v *ResourceTypes) *ResourcesUpdate {
	return _u.SetLionResourceTypesID(v.ID)
}

// AddLionMenuIDs adds the "lion_menus" edge to the Menus entity by IDs.
func (_u *ResourcesUpdate) AddLionMenuIDs(ids ...int) *ResourcesUpdate {
	_u.mutation.AddLionMenuIDs(ids...)
	return _u
}

// AddLionMenus adds the "lion_menus" edges to the Menus entity.
func (_u *ResourcesUpdate) AddLionMenus(v ...*Menus) *ResourcesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionMenuIDs(ids...)
}

// AddLionResourceScopeIDs adds the "lion_resource_scopes" edge to the ResourceScopes entity by IDs.
func (_u *ResourcesUpdate) AddLionResourceScopeIDs(ids ...int) *ResourcesUpdate {
	_u.mutation.AddLionResourceScopeIDs(ids...)
	return _u
}

// AddLionResourceScopes adds the "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ResourcesUpdate) AddLionResourceScopes(v ...*ResourceScopes) *ResourcesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionResourceScopeIDs(ids...)
}

// Mutation returns the ResourcesMutation object of the builder.
func (_u *ResourcesUpdate) Mutation() *ResourcesMutation {
	return _u.mutation
}

// ClearLionResourceTypes clears the "lion_resource_types" edge to the ResourceTypes entity.
func (_u *ResourcesUpdate) ClearLionResourceTypes() *ResourcesUpdate {
	_u.mutation.ClearLionResourceTypes()
	return _u
}

// ClearLionMenus clears all "lion_menus" edges to the Menus entity.
func (_u *ResourcesUpdate) ClearLionMenus() *ResourcesUpdate {
	_u.mutation.ClearLionMenus()
	return _u
}

// RemoveLionMenuIDs removes the "lion_menus" edge to Menus entities by IDs.
func (_u *ResourcesUpdate) RemoveLionMenuIDs(ids ...int) *ResourcesUpdate {
	_u.mutation.RemoveLionMenuIDs(ids...)
	return _u
}

// RemoveLionMenus removes "lion_menus" edges to Menus entities.
func (_u *ResourcesUpdate) RemoveLionMenus(v ...*Menus) *ResourcesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionMenuIDs(ids...)
}

// ClearLionResourceScopes clears all "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ResourcesUpdate) ClearLionResourceScopes() *ResourcesUpdate {
	_u.mutation.ClearLionResourceScopes()
	return _u
}

// RemoveLionResourceScopeIDs removes the "lion_resource_scopes" edge to ResourceScopes entities by IDs.
func (_u *ResourcesUpdate) RemoveLionResourceScopeIDs(ids ...int) *ResourcesUpdate {
	_u.mutation.RemoveLionResourceScopeIDs(ids...)
	return _u
}

// RemoveLionResourceScopes removes "lion_resource_scopes" edges to ResourceScopes entities.
func (_u *ResourcesUpdate) RemoveLionResourceScopes(v ...*ResourceScopes) *ResourcesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionResourceScopeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourcesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourcesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourcesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourcesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourcesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resources.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourcesUpdate) check() error {
	if v, ok := _u.mutation.ResourceTypeID(); ok {
		if err := resources.ResourceTypeIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_type_id", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_type_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceTypeCode(); ok {
		if err := resources.ResourceTypeCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type_code", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_type_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceCode(); ok {
		if err := resources.ServiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "service_code", err: fmt.Errorf(`lion: validator failed for field "Resources.service_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := resources.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`lion: validator failed for field "Resources.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := resources.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`lion: validator failed for field "Resources.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourcePath(); ok {
		if err := resources.ResourcePathValidator(v); err != nil {
			return &ValidationError{Name: "resource_path", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Grn(); ok {
		if err := resources.GrnValidator(v); err != nil {
			return &ValidationError{Name: "grn", err: fmt.Errorf(`lion: validator failed for field "Resources.grn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := resources.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`lion: validator failed for field "Resources.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resources.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "Resources.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceStatusCode(); ok {
		if err := resources.ResourceStatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_status_code", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_status_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locator(); ok {
		if err := resources.LocatorValidator(v); err != nil {
			return &ValidationError{Name: "locator", err: fmt.Errorf(`lion: validator failed for field "Resources.locator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visual(); ok {
		if err := resources.VisualValidator(v); err != nil {
			return &ValidationError{Name: "visual", err: fmt.Errorf(`lion: validator failed for field "Resources.visual": %w`, err)}
		}
	}
	if _u.mutation.LionResourceTypesCleared() && len(_u.mutation.LionResourceTypesIDs()) > 0 {
		return errors.New(`lion: clearing a required unique edge "Resources.lion_resource_types"`)
	}
	return nil
}

func (_u *ResourcesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resources.Table, resources.Columns, sqlgraph.NewFieldSpec(resources.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resources.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resources.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resources.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(resources.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(resources.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(resources.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(resources.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(resources.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(resources.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(resources.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(resources.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResourceTypeCode(); ok {
		_spec.SetField(resources.FieldResourceTypeCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceCode(); ok {
		_spec.SetField(resources.FieldServiceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(resources.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(resources.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourcePath(); ok {
		_spec.SetField(resources.FieldResourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Grn(); ok {
		_spec.SetField(resources.FieldGrn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(resources.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resources.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(resources.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resources.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceType(); ok {
		_spec.AddField(resources.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceStatus(); ok {
		_spec.SetField(resources.FieldResourceStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceStatus(); ok {
		_spec.AddField(resources.FieldResourceStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceStatusCode(); ok {
		_spec.SetField(resources.FieldResourceStatusCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(resources.FieldVisibility, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(resources.FieldVisibility, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(resources.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(resources.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Locator(); ok {
		_spec.SetField(resources.FieldLocator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visual(); ok {
		_spec.SetField(resources.FieldVisual, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(resources.FieldManifest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resources.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protected(); ok {
		_spec.SetField(resources.FieldProtected, field.TypeBool, value)
	}
	if _u.mutation.LionResourceTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resources.LionResourceTypesTable,
			Columns: []string{resources.LionResourceTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcetypes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resources.LionResourceTypesTable,
			Columns: []string{resources.LionResourceTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcetypes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionMenusIDs(); len(nodes) > 0 && !_u.mutation.LionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionResourceScopesIDs(); len(nodes) > 0 && !_u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resources.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourcesUpdateOne is the builder for updating a single Resources entity.
type ResourcesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourcesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourcesUpdateOne) SetUpdatedAt(v time.Time) *ResourcesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResourcesUpdateOne) SetDeletedAt(v time.Time) *ResourcesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableDeletedAt(v *time.Time) *ResourcesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResourcesUpdateOne) ClearDeletedAt() *ResourcesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ResourcesUpdateOne) SetCreatedBy(v int64) *ResourcesUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableCreatedBy(v *int64) *ResourcesUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ResourcesUpdateOne) AddCreatedBy(v int64) *ResourcesUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ResourcesUpdateOne) ClearCreatedBy() *ResourcesUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ResourcesUpdateOne) SetUpdatedBy(v int64) *ResourcesUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableUpdatedBy(v *int64) *ResourcesUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ResourcesUpdateOne) AddUpdatedBy(v int64) *ResourcesUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ResourcesUpdateOne) ClearUpdatedBy() *ResourcesUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ResourcesUpdateOne) SetParentID(v int64) *ResourcesUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableParentID(v *int64) *ResourcesUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *ResourcesUpdateOne) AddParentID(v int64) *ResourcesUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetResourceTypeID sets the "resource_type_id" field.
func (_u *ResourcesUpdateOne) SetResourceTypeID(v int) *ResourcesUpdateOne {
	_u.mutation.SetResourceTypeID(v)
	return _u
}

// SetNillableResourceTypeID sets the "resource_type_id" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourceTypeID(v *int) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourceTypeID(*v)
	}
	return _u
}

// SetResourceTypeCode sets the "resource_type_code" field.
func (_u *ResourcesUpdateOne) SetResourceTypeCode(v string) *ResourcesUpdateOne {
	_u.mutation.SetResourceTypeCode(v)
	return _u
}

// SetNillableResourceTypeCode sets the "resource_type_code" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourceTypeCode(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourceTypeCode(*v)
	}
	return _u
}

// SetServiceCode sets the "service_code" field.
func (_u *ResourcesUpdateOne) SetServiceCode(v string) *ResourcesUpdateOne {
	_u.mutation.SetServiceCode(v)
	return _u
}

// SetNillableServiceCode sets the "service_code" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableServiceCode(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetServiceCode(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ResourcesUpdateOne) SetTenantID(v string) *ResourcesUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableTenantID(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ResourcesUpdateOne) SetRegion(v string) *ResourcesUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableRegion(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetResourcePath sets the "resource_path" field.
func (_u *ResourcesUpdateOne) SetResourcePath(v string) *ResourcesUpdateOne {
	_u.mutation.SetResourcePath(v)
	return _u
}

// SetNillableResourcePath sets the "resource_path" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourcePath(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourcePath(*v)
	}
	return _u
}

// SetGrn sets the "grn" field.
func (_u *ResourcesUpdateOne) SetGrn(v string) *ResourcesUpdateOne {
	_u.mutation.SetGrn(v)
	return _u
}

// SetNillableGrn sets the "grn" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableGrn(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetGrn(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ResourcesUpdateOne) SetCode(v string) *ResourcesUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableCode(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ResourcesUpdateOne) SetName(v string) *ResourcesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableName(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ResourcesUpdateOne) SetDisplayName(v string) *ResourcesUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableDisplayName(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourcesUpdateOne) SetResourceType(v int) *ResourcesUpdateOne {
	_u.mutation.ResetResourceType()
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourceType(v *int) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// AddResourceType adds value to the "resource_type" field.
func (_u *ResourcesUpdateOne) AddResourceType(v int) *ResourcesUpdateOne {
	_u.mutation.AddResourceType(v)
	return _u
}

// SetResourceStatus sets the "resource_status" field.
func (_u *ResourcesUpdateOne) SetResourceStatus(v int) *ResourcesUpdateOne {
	_u.mutation.ResetResourceStatus()
	_u.mutation.SetResourceStatus(v)
	return _u
}

// SetNillableResourceStatus sets the "resource_status" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourceStatus(v *int) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourceStatus(*v)
	}
	return _u
}

// AddResourceStatus adds value to the "resource_status" field.
func (_u *ResourcesUpdateOne) AddResourceStatus(v int) *ResourcesUpdateOne {
	_u.mutation.AddResourceStatus(v)
	return _u
}

// SetResourceStatusCode sets the "resource_status_code" field.
func (_u *ResourcesUpdateOne) SetResourceStatusCode(v string) *ResourcesUpdateOne {
	_u.mutation.SetResourceStatusCode(v)
	return _u
}

// SetNillableResourceStatusCode sets the "resource_status_code" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableResourceStatusCode(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetResourceStatusCode(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ResourcesUpdateOne) SetVisibility(v int) *ResourcesUpdateOne {
	_u.mutation.ResetVisibility()
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableVisibility(v *int) *ResourcesUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// AddVisibility adds value to the "visibility" field.
func (_u *ResourcesUpdateOne) AddVisibility(v int) *ResourcesUpdateOne {
	_u.mutation.AddVisibility(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ResourcesUpdateOne) SetSortOrder(v int) *ResourcesUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableSortOrder(v *int) *ResourcesUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ResourcesUpdateOne) AddSortOrder(v int) *ResourcesUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetLocator sets the "locator" field.
func (_u *ResourcesUpdateOne) SetLocator(v string) *ResourcesUpdateOne {
	_u.mutation.SetLocator(v)
	return _u
}

// SetNillableLocator sets the "locator" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableLocator(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetLocator(*v)
	}
	return _u
}

// SetVisual sets the "visual" field.
func (_u *ResourcesUpdateOne) SetVisual(v string) *ResourcesUpdateOne {
	_u.mutation.SetVisual(v)
	return _u
}

// SetNillableVisual sets the "visual" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableVisual(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetVisual(*v)
	}
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *ResourcesUpdateOne) SetManifest(v string) *ResourcesUpdateOne {
	_u.mutation.SetManifest(v)
	return _u
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableManifest(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetManifest(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResourcesUpdateOne) SetDescription(v string) *ResourcesUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableDescription(v *string) *ResourcesUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProtected sets the "protected" field.
func (_u *ResourcesUpdateOne) SetProtected(v bool) *ResourcesUpdateOne {
	_u.mutation.SetProtected(v)
	return _u
}

// SetNillableProtected sets the "protected" field if the given value is not nil.
func (_u *ResourcesUpdateOne) SetNillableProtected(v *bool) *ResourcesUpdateOne {
	if v != nil {
		_u.SetProtected(*v)
	}
	return _u
}

// SetLionResourceTypesID sets the "lion_resource_types" edge to the ResourceTypes entity by ID.
func (_u *ResourcesUpdateOne) SetLionResourceTypesID(id int) *ResourcesUpdateOne {
	_u.mutation.SetLionResourceTypesID(id)
	return _u
}

// SetLionResourceTypes sets the "lion_resource_types" edge to the ResourceTypes entity.
func (_u *ResourcesUpdateOne) SetLionResourceTypes(v *ResourceTypes) *ResourcesUpdateOne {
	return _u.SetLionResourceTypesID(v.ID)
}

// AddLionMenuIDs adds the "lion_menus" edge to the Menus entity by IDs.
func (_u *ResourcesUpdateOne) AddLionMenuIDs(ids ...int) *ResourcesUpdateOne {
	_u.mutation.AddLionMenuIDs(ids...)
	return _u
}

// AddLionMenus adds the "lion_menus" edges to the Menus entity.
func (_u *ResourcesUpdateOne) AddLionMenus(v ...*Menus) *ResourcesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionMenuIDs(ids...)
}

// AddLionResourceScopeIDs adds the "lion_resource_scopes" edge to the ResourceScopes entity by IDs.
func (_u *ResourcesUpdateOne) AddLionResourceScopeIDs(ids ...int) *ResourcesUpdateOne {
	_u.mutation.AddLionResourceScopeIDs(ids...)
	return _u
}

// AddLionResourceScopes adds the "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ResourcesUpdateOne) AddLionResourceScopes(v ...*ResourceScopes) *ResourcesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionResourceScopeIDs(ids...)
}

// Mutation returns the ResourcesMutation object of the builder.
func (_u *ResourcesUpdateOne) Mutation() *ResourcesMutation {
	return _u.mutation
}

// ClearLionResourceTypes clears the "lion_resource_types" edge to the ResourceTypes entity.
func (_u *ResourcesUpdateOne) ClearLionResourceTypes() *ResourcesUpdateOne {
	_u.mutation.ClearLionResourceTypes()
	return _u
}

// ClearLionMenus clears all "lion_menus" edges to the Menus entity.
func (_u *ResourcesUpdateOne) ClearLionMenus() *ResourcesUpdateOne {
	_u.mutation.ClearLionMenus()
	return _u
}

// RemoveLionMenuIDs removes the "lion_menus" edge to Menus entities by IDs.
func (_u *ResourcesUpdateOne) RemoveLionMenuIDs(ids ...int) *ResourcesUpdateOne {
	_u.mutation.RemoveLionMenuIDs(ids...)
	return _u
}

// RemoveLionMenus removes "lion_menus" edges to Menus entities.
func (_u *ResourcesUpdateOne) RemoveLionMenus(v ...*Menus) *ResourcesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionMenuIDs(ids...)
}

// ClearLionResourceScopes clears all "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ResourcesUpdateOne) ClearLionResourceScopes() *ResourcesUpdateOne {
	_u.mutation.ClearLionResourceScopes()
	return _u
}

// RemoveLionResourceScopeIDs removes the "lion_resource_scopes" edge to ResourceScopes entities by IDs.
func (_u *ResourcesUpdateOne) RemoveLionResourceScopeIDs(ids ...int) *ResourcesUpdateOne {
	_u.mutation.RemoveLionResourceScopeIDs(ids...)
	return _u
}

// RemoveLionResourceScopes removes "lion_resource_scopes" edges to ResourceScopes entities.
func (_u *ResourcesUpdateOne) RemoveLionResourceScopes(v ...*ResourceScopes) *ResourcesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionResourceScopeIDs(ids...)
}

// Where appends a list predicates to the ResourcesUpdate builder.
func (_u *ResourcesUpdateOne) Where(ps ...predicate.Resources) *ResourcesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourcesUpdateOne) Select(field string, fields ...string) *ResourcesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resources entity.
func (_u *ResourcesUpdateOne) Save(ctx context.Context) (*Resources, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourcesUpdateOne) SaveX(ctx context.Context) *Resources {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourcesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourcesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourcesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resources.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourcesUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceTypeID(); ok {
		if err := resources.ResourceTypeIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_type_id", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_type_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceTypeCode(); ok {
		if err := resources.ResourceTypeCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type_code", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_type_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceCode(); ok {
		if err := resources.ServiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "service_code", err: fmt.Errorf(`lion: validator failed for field "Resources.service_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := resources.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`lion: validator failed for field "Resources.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := resources.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`lion: validator failed for field "Resources.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourcePath(); ok {
		if err := resources.ResourcePathValidator(v); err != nil {
			return &ValidationError{Name: "resource_path", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Grn(); ok {
		if err := resources.GrnValidator(v); err != nil {
			return &ValidationError{Name: "grn", err: fmt.Errorf(`lion: validator failed for field "Resources.grn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := resources.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`lion: validator failed for field "Resources.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := resources.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "Resources.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceStatusCode(); ok {
		if err := resources.ResourceStatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "resource_status_code", err: fmt.Errorf(`lion: validator failed for field "Resources.resource_status_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Locator(); ok {
		if err := resources.LocatorValidator(v); err != nil {
			return &ValidationError{Name: "locator", err: fmt.Errorf(`lion: validator failed for field "Resources.locator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visual(); ok {
		if err := resources.VisualValidator(v); err != nil {
			return &ValidationError{Name: "visual", err: fmt.Errorf(`lion: validator failed for field "Resources.visual": %w`, err)}
		}
	}
	if _u.mutation.LionResourceTypesCleared() && len(_u.mutation.LionResourceTypesIDs()) > 0 {
		return errors.New(`lion: clearing a required unique edge "Resources.lion_resource_types"`)
	}
	return nil
}

func (_u *ResourcesUpdateOne) sqlSave(ctx context.Context) (_node *Resources, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resources.Table, resources.Columns, sqlgraph.NewFieldSpec(resources.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "Resources.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resources.FieldID)
		for _, f := range fields {
			if !resources.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != resources.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resources.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resources.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resources.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(resources.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(resources.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(resources.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(resources.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(resources.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(resources.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(resources.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(resources.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ResourceTypeCode(); ok {
		_spec.SetField(resources.FieldResourceTypeCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceCode(); ok {
		_spec.SetField(resources.FieldServiceCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(resources.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(resources.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourcePath(); ok {
		_spec.SetField(resources.FieldResourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Grn(); ok {
		_spec.SetField(resources.FieldGrn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(resources.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resources.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(resources.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resources.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceType(); ok {
		_spec.AddField(resources.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceStatus(); ok {
		_spec.SetField(resources.FieldResourceStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceStatus(); ok {
		_spec.AddField(resources.FieldResourceStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceStatusCode(); ok {
		_spec.SetField(resources.FieldResourceStatusCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(resources.FieldVisibility, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVisibility(); ok {
		_spec.AddField(resources.FieldVisibility, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(resources.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(resources.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Locator(); ok {
		_spec.SetField(resources.FieldLocator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visual(); ok {
		_spec.SetField(resources.FieldVisual, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(resources.FieldManifest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(resources.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protected(); ok {
		_spec.SetField(resources.FieldProtected, field.TypeBool, value)
	}
	if _u.mutation.LionResourceTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resources.LionResourceTypesTable,
			Columns: []string{resources.LionResourceTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcetypes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resources.LionResourceTypesTable,
			Columns: []string{resources.LionResourceTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcetypes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionMenusIDs(); len(nodes) > 0 && !_u.mutation.LionMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionMenusTable,
			Columns: []string{resources.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionResourceScopesIDs(); len(nodes) > 0 && !_u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resources.LionResourceScopesTable,
			Columns: []string{resources.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Resources{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resources.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
