// Code generated by ent, DO NOT EDIT.

package lion

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/resources"
)

// Resources is the model entity for the Resources schema.
type Resources struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// 父资源 ID，为 0 表示顶级资源
	ParentID int64 `json:"parent_id,omitempty"`
	// 资源名称
	Code string `json:"code,omitempty"`
	// 友好展示名称
	DisplayName string `json:"display_name,omitempty"`
	// 用途类型，对应 api/known/admin/v1/common.proto 中定义
	ResourceType int `json:"resource_type,omitempty"`
	// 是否启用该资源项，禁用后完全不可访问
	ResourceStatus int `json:"resource_status,omitempty"`
	// 可见性定义，对应 api/known/admin/v1/common.proto 中定义
	Visibility int `json:"visibility,omitempty"`
	// 资源排序顺序，用于同级资源的显示顺序，数值越小排序越靠前，建议使用 10 的倍数便于后续插入，默认值：100，范围：1-9999
	SortOrder int `json:"sort_order,omitempty"`
	// 资源路径
	Locator string `json:"locator,omitempty"`
	// 图标名称，如 UserOutlined
	Visual string `json:"visual,omitempty"`
	// 组件名称，如 UserOutlined
	Manifest string `json:"manifest,omitempty"`
	// 详细描述
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourcesQuery when eager-loading is set.
	Edges        ResourcesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResourcesEdges holds the relations/edges for other nodes in the graph.
type ResourcesEdges struct {
	// LionResourceScopes holds the value of the lion_resource_scopes edge.
	LionResourceScopes []*ResourceScopes `json:"lion_resource_scopes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LionResourceScopesOrErr returns the LionResourceScopes value or an error if the edge
// was not loaded in eager-loading.
func (e ResourcesEdges) LionResourceScopesOrErr() ([]*ResourceScopes, error) {
	if e.loadedTypes[0] {
		return e.LionResourceScopes, nil
	}
	return nil, &NotLoadedError{edge: "lion_resource_scopes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resources) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resources.FieldID, resources.FieldCreatedBy, resources.FieldUpdatedBy, resources.FieldParentID, resources.FieldResourceType, resources.FieldResourceStatus, resources.FieldVisibility, resources.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case resources.FieldCode, resources.FieldDisplayName, resources.FieldLocator, resources.FieldVisual, resources.FieldManifest, resources.FieldDescription:
			values[i] = new(sql.NullString)
		case resources.FieldCreatedAt, resources.FieldUpdatedAt, resources.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resources fields.
func (_m *Resources) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resources.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case resources.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resources.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resources.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case resources.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case resources.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case resources.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		case resources.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case resources.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case resources.FieldResourceType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = int(value.Int64)
			}
		case resources.FieldResourceStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resource_status", values[i])
			} else if value.Valid {
				_m.ResourceStatus = int(value.Int64)
			}
		case resources.FieldVisibility:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = int(value.Int64)
			}
		case resources.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case resources.FieldLocator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locator", values[i])
			} else if value.Valid {
				_m.Locator = value.String
			}
		case resources.FieldVisual:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visual", values[i])
			} else if value.Valid {
				_m.Visual = value.String
			}
		case resources.FieldManifest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest", values[i])
			} else if value.Valid {
				_m.Manifest = value.String
			}
		case resources.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resources.
// This includes values selected through modifiers, order, etc.
func (_m *Resources) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLionResourceScopes queries the "lion_resource_scopes" edge of the Resources entity.
func (_m *Resources) QueryLionResourceScopes() *ResourceScopesQuery {
	return NewResourcesClient(_m.config).QueryLionResourceScopes(_m)
}

// Update returns a builder for updating this Resources.
// Note that you need to call Resources.Unwrap() before calling this method if this Resources
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Resources) Update() *ResourcesUpdateOne {
	return NewResourcesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Resources entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Resources) Unwrap() *Resources {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: Resources is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Resources) String() string {
	var builder strings.Builder
	builder.WriteString("Resources(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceType))
	builder.WriteString(", ")
	builder.WriteString("resource_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceStatus))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("locator=")
	builder.WriteString(_m.Locator)
	builder.WriteString(", ")
	builder.WriteString("visual=")
	builder.WriteString(_m.Visual)
	builder.WriteString(", ")
	builder.WriteString("manifest=")
	builder.WriteString(_m.Manifest)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// ResourcesSlice is a parsable slice of Resources.
type ResourcesSlice []*Resources
