// Code generated by ent, DO NOT EDIT.

package lion

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/resources"
)

// Resources is the model entity for the Resources schema.
type Resources struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 父菜单 ID，为 0 表示顶级菜单
	ParentID int `json:"parent_id,omitempty"`
	// 菜单名称
	Name string `json:"name,omitempty"`
	// 菜单路径
	Path string `json:"path,omitempty"`
	// 国际化标识
	I18nName string `json:"i18n_name,omitempty"`
	// 图标名称，如 UserOutlined
	Icon string `json:"icon,omitempty"`
	// 排序权重，越小越靠前
	OrderWeight int `json:"order_weight,omitempty"`
	// 菜单用途类型，如 1=admin 后台
	MenuType int `json:"menu_type,omitempty"`
	// 是否启用该菜单项，禁用后完全不可访问
	Enabled bool `json:"enabled,omitempty"`
	// 是否在菜单中隐藏该节点
	HideInMenu bool `json:"hide_in_menu,omitempty"`
	// 是否隐藏该节点的子菜单
	HideChildrenInMenu bool `json:"hide_children_in_menu,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourcesQuery when eager-loading is set.
	Edges        ResourcesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResourcesEdges holds the relations/edges for other nodes in the graph.
type ResourcesEdges struct {
	// LionRoleResources holds the value of the lion_role_resources edge.
	LionRoleResources []*RoleResources `json:"lion_role_resources,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LionRoleResourcesOrErr returns the LionRoleResources value or an error if the edge
// was not loaded in eager-loading.
func (e ResourcesEdges) LionRoleResourcesOrErr() ([]*RoleResources, error) {
	if e.loadedTypes[0] {
		return e.LionRoleResources, nil
	}
	return nil, &NotLoadedError{edge: "lion_role_resources"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Resources) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resources.FieldEnabled, resources.FieldHideInMenu, resources.FieldHideChildrenInMenu:
			values[i] = new(sql.NullBool)
		case resources.FieldID, resources.FieldParentID, resources.FieldOrderWeight, resources.FieldMenuType:
			values[i] = new(sql.NullInt64)
		case resources.FieldName, resources.FieldPath, resources.FieldI18nName, resources.FieldIcon:
			values[i] = new(sql.NullString)
		case resources.FieldCreatedAt, resources.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Resources fields.
func (_m *Resources) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resources.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case resources.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resources.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resources.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = int(value.Int64)
			}
		case resources.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case resources.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case resources.FieldI18nName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field i18n_name", values[i])
			} else if value.Valid {
				_m.I18nName = value.String
			}
		case resources.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case resources.FieldOrderWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_weight", values[i])
			} else if value.Valid {
				_m.OrderWeight = int(value.Int64)
			}
		case resources.FieldMenuType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field menu_type", values[i])
			} else if value.Valid {
				_m.MenuType = int(value.Int64)
			}
		case resources.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case resources.FieldHideInMenu:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hide_in_menu", values[i])
			} else if value.Valid {
				_m.HideInMenu = value.Bool
			}
		case resources.FieldHideChildrenInMenu:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hide_children_in_menu", values[i])
			} else if value.Valid {
				_m.HideChildrenInMenu = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Resources.
// This includes values selected through modifiers, order, etc.
func (_m *Resources) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLionRoleResources queries the "lion_role_resources" edge of the Resources entity.
func (_m *Resources) QueryLionRoleResources() *RoleResourcesQuery {
	return NewResourcesClient(_m.config).QueryLionRoleResources(_m)
}

// Update returns a builder for updating this Resources.
// Note that you need to call Resources.Unwrap() before calling this method if this Resources
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Resources) Update() *ResourcesUpdateOne {
	return NewResourcesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Resources entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Resources) Unwrap() *Resources {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: Resources is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Resources) String() string {
	var builder strings.Builder
	builder.WriteString("Resources(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("i18n_name=")
	builder.WriteString(_m.I18nName)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("order_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderWeight))
	builder.WriteString(", ")
	builder.WriteString("menu_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuType))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("hide_in_menu=")
	builder.WriteString(fmt.Sprintf("%v", _m.HideInMenu))
	builder.WriteString(", ")
	builder.WriteString("hide_children_in_menu=")
	builder.WriteString(fmt.Sprintf("%v", _m.HideChildrenInMenu))
	builder.WriteByte(')')
	return builder.String()
}

// ResourcesSlice is a parsable slice of Resources.
type ResourcesSlice []*Resources
