// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/menus"
	"github.com/grpc-kit/pkg/lion/rolemenus"
	"github.com/grpc-kit/pkg/lion/roles"
)

// RoleMenusCreate is the builder for creating a RoleMenus entity.
type RoleMenusCreate struct {
	config
	mutation *RoleMenusMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoleMenusCreate) SetCreatedAt(v time.Time) *RoleMenusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoleMenusCreate) SetNillableCreatedAt(v *time.Time) *RoleMenusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoleMenusCreate) SetUpdatedAt(v time.Time) *RoleMenusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoleMenusCreate) SetNillableUpdatedAt(v *time.Time) *RoleMenusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *RoleMenusCreate) SetRoleID(v int) *RoleMenusCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetMenuID sets the "menu_id" field.
func (_c *RoleMenusCreate) SetMenuID(v int) *RoleMenusCreate {
	_c.mutation.SetMenuID(v)
	return _c
}

// SetLionRolesID sets the "lion_roles" edge to the Roles entity by ID.
func (_c *RoleMenusCreate) SetLionRolesID(id int) *RoleMenusCreate {
	_c.mutation.SetLionRolesID(id)
	return _c
}

// SetLionRoles sets the "lion_roles" edge to the Roles entity.
func (_c *RoleMenusCreate) SetLionRoles(v *Roles) *RoleMenusCreate {
	return _c.SetLionRolesID(v.ID)
}

// SetLionMenusID sets the "lion_menus" edge to the Menus entity by ID.
func (_c *RoleMenusCreate) SetLionMenusID(id int) *RoleMenusCreate {
	_c.mutation.SetLionMenusID(id)
	return _c
}

// SetLionMenus sets the "lion_menus" edge to the Menus entity.
func (_c *RoleMenusCreate) SetLionMenus(v *Menus) *RoleMenusCreate {
	return _c.SetLionMenusID(v.ID)
}

// Mutation returns the RoleMenusMutation object of the builder.
func (_c *RoleMenusCreate) Mutation() *RoleMenusMutation {
	return _c.mutation
}

// Save creates the RoleMenus in the database.
func (_c *RoleMenusCreate) Save(ctx context.Context) (*RoleMenus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoleMenusCreate) SaveX(ctx context.Context) *RoleMenus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleMenusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleMenusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoleMenusCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rolemenus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rolemenus.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoleMenusCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "RoleMenus.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "RoleMenus.updated_at"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`lion: missing required field "RoleMenus.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := rolemenus.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`lion: validator failed for field "RoleMenus.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MenuID(); !ok {
		return &ValidationError{Name: "menu_id", err: errors.New(`lion: missing required field "RoleMenus.menu_id"`)}
	}
	if v, ok := _c.mutation.MenuID(); ok {
		if err := rolemenus.MenuIDValidator(v); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`lion: validator failed for field "RoleMenus.menu_id": %w`, err)}
		}
	}
	if len(_c.mutation.LionRolesIDs()) == 0 {
		return &ValidationError{Name: "lion_roles", err: errors.New(`lion: missing required edge "RoleMenus.lion_roles"`)}
	}
	if len(_c.mutation.LionMenusIDs()) == 0 {
		return &ValidationError{Name: "lion_menus", err: errors.New(`lion: missing required edge "RoleMenus.lion_menus"`)}
	}
	return nil
}

func (_c *RoleMenusCreate) sqlSave(ctx context.Context) (*RoleMenus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoleMenusCreate) createSpec() (*RoleMenus, *sqlgraph.CreateSpec) {
	var (
		_node = &RoleMenus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolemenus.Table, sqlgraph.NewFieldSpec(rolemenus.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rolemenus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rolemenus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.LionRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolemenus.LionRolesTable,
			Columns: []string{rolemenus.LionRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roles.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LionMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolemenus.LionMenusTable,
			Columns: []string{rolemenus.LionMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menus.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MenuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoleMenusCreateBulk is the builder for creating many RoleMenus entities in bulk.
type RoleMenusCreateBulk struct {
	config
	err      error
	builders []*RoleMenusCreate
}

// Save creates the RoleMenus entities in the database.
func (_c *RoleMenusCreateBulk) Save(ctx context.Context) ([]*RoleMenus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoleMenus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleMenusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoleMenusCreateBulk) SaveX(ctx context.Context) []*RoleMenus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleMenusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleMenusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
