// Code generated by ent, DO NOT EDIT.

package lion

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/policies"
	"github.com/grpc-kit/pkg/lion/rolepolicies"
	"github.com/grpc-kit/pkg/lion/roles"
)

// RolePolicies is the model entity for the RolePolicies schema.
type RolePolicies struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// 关联 lion_roles 表的角色 ID
	RoleID int `json:"role_id,omitempty"`
	// 关联 lion_policies 表的策略 ID
	PolicyID int `json:"policy_id,omitempty"`
	// 元数据，用于存储来源等扩展属性
	Metadata map[string]string `json:"metadata,omitempty"`
	// 绑定关系描述
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RolePoliciesQuery when eager-loading is set.
	Edges        RolePoliciesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RolePoliciesEdges holds the relations/edges for other nodes in the graph.
type RolePoliciesEdges struct {
	// LionRoles holds the value of the lion_roles edge.
	LionRoles *Roles `json:"lion_roles,omitempty"`
	// LionPolicies holds the value of the lion_policies edge.
	LionPolicies *Policies `json:"lion_policies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LionRolesOrErr returns the LionRoles value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RolePoliciesEdges) LionRolesOrErr() (*Roles, error) {
	if e.LionRoles != nil {
		return e.LionRoles, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: roles.Label}
	}
	return nil, &NotLoadedError{edge: "lion_roles"}
}

// LionPoliciesOrErr returns the LionPolicies value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RolePoliciesEdges) LionPoliciesOrErr() (*Policies, error) {
	if e.LionPolicies != nil {
		return e.LionPolicies, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: policies.Label}
	}
	return nil, &NotLoadedError{edge: "lion_policies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RolePolicies) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolepolicies.FieldMetadata:
			values[i] = new([]byte)
		case rolepolicies.FieldID, rolepolicies.FieldCreatedBy, rolepolicies.FieldUpdatedBy, rolepolicies.FieldRoleID, rolepolicies.FieldPolicyID:
			values[i] = new(sql.NullInt64)
		case rolepolicies.FieldDescription:
			values[i] = new(sql.NullString)
		case rolepolicies.FieldCreatedAt, rolepolicies.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RolePolicies fields.
func (_m *RolePolicies) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolepolicies.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rolepolicies.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rolepolicies.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rolepolicies.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case rolepolicies.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case rolepolicies.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = int(value.Int64)
			}
		case rolepolicies.FieldPolicyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_id", values[i])
			} else if value.Valid {
				_m.PolicyID = int(value.Int64)
			}
		case rolepolicies.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case rolepolicies.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RolePolicies.
// This includes values selected through modifiers, order, etc.
func (_m *RolePolicies) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLionRoles queries the "lion_roles" edge of the RolePolicies entity.
func (_m *RolePolicies) QueryLionRoles() *RolesQuery {
	return NewRolePoliciesClient(_m.config).QueryLionRoles(_m)
}

// QueryLionPolicies queries the "lion_policies" edge of the RolePolicies entity.
func (_m *RolePolicies) QueryLionPolicies() *PoliciesQuery {
	return NewRolePoliciesClient(_m.config).QueryLionPolicies(_m)
}

// Update returns a builder for updating this RolePolicies.
// Note that you need to call RolePolicies.Unwrap() before calling this method if this RolePolicies
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RolePolicies) Update() *RolePoliciesUpdateOne {
	return NewRolePoliciesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RolePolicies entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RolePolicies) Unwrap() *RolePolicies {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: RolePolicies is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RolePolicies) String() string {
	var builder strings.Builder
	builder.WriteString("RolePolicies(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("policy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyID))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// RolePoliciesSlice is a parsable slice of RolePolicies.
type RolePoliciesSlice []*RolePolicies
