// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/predicate"
	"github.com/grpc-kit/pkg/lion/resourcescopes"
	"github.com/grpc-kit/pkg/lion/scopes"
)

// ScopesUpdate is the builder for updating Scopes entities.
type ScopesUpdate struct {
	config
	hooks    []Hook
	mutation *ScopesMutation
}

// Where appends a list predicates to the ScopesUpdate builder.
func (_u *ScopesUpdate) Where(ps ...predicate.Scopes) *ScopesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScopesUpdate) SetUpdatedAt(v time.Time) *ScopesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ScopesUpdate) SetDeletedAt(v time.Time) *ScopesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ScopesUpdate) SetNillableDeletedAt(v *time.Time) *ScopesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ScopesUpdate) ClearDeletedAt() *ScopesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ScopesUpdate) SetName(v string) *ScopesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScopesUpdate) SetNillableName(v *string) *ScopesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ScopesUpdate) SetDisplayName(v string) *ScopesUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ScopesUpdate) SetNillableDisplayName(v *string) *ScopesUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// AddLionResourceScopeIDs adds the "lion_resource_scopes" edge to the ResourceScopes entity by IDs.
func (_u *ScopesUpdate) AddLionResourceScopeIDs(ids ...int) *ScopesUpdate {
	_u.mutation.AddLionResourceScopeIDs(ids...)
	return _u
}

// AddLionResourceScopes adds the "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ScopesUpdate) AddLionResourceScopes(v ...*ResourceScopes) *ScopesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionResourceScopeIDs(ids...)
}

// Mutation returns the ScopesMutation object of the builder.
func (_u *ScopesUpdate) Mutation() *ScopesMutation {
	return _u.mutation
}

// ClearLionResourceScopes clears all "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ScopesUpdate) ClearLionResourceScopes() *ScopesUpdate {
	_u.mutation.ClearLionResourceScopes()
	return _u
}

// RemoveLionResourceScopeIDs removes the "lion_resource_scopes" edge to ResourceScopes entities by IDs.
func (_u *ScopesUpdate) RemoveLionResourceScopeIDs(ids ...int) *ScopesUpdate {
	_u.mutation.RemoveLionResourceScopeIDs(ids...)
	return _u
}

// RemoveLionResourceScopes removes "lion_resource_scopes" edges to ResourceScopes entities.
func (_u *ScopesUpdate) RemoveLionResourceScopes(v ...*ResourceScopes) *ScopesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionResourceScopeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScopesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScopesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScopesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScopesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScopesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scopes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScopesUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scopes.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "Scopes.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScopesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scopes.Table, scopes.Columns, sqlgraph.NewFieldSpec(scopes.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scopes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(scopes.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(scopes.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scopes.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(scopes.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionResourceScopesIDs(); len(nodes) > 0 && !_u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scopes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScopesUpdateOne is the builder for updating a single Scopes entity.
type ScopesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScopesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScopesUpdateOne) SetUpdatedAt(v time.Time) *ScopesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ScopesUpdateOne) SetDeletedAt(v time.Time) *ScopesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ScopesUpdateOne) SetNillableDeletedAt(v *time.Time) *ScopesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ScopesUpdateOne) ClearDeletedAt() *ScopesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ScopesUpdateOne) SetName(v string) *ScopesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScopesUpdateOne) SetNillableName(v *string) *ScopesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ScopesUpdateOne) SetDisplayName(v string) *ScopesUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ScopesUpdateOne) SetNillableDisplayName(v *string) *ScopesUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// AddLionResourceScopeIDs adds the "lion_resource_scopes" edge to the ResourceScopes entity by IDs.
func (_u *ScopesUpdateOne) AddLionResourceScopeIDs(ids ...int) *ScopesUpdateOne {
	_u.mutation.AddLionResourceScopeIDs(ids...)
	return _u
}

// AddLionResourceScopes adds the "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ScopesUpdateOne) AddLionResourceScopes(v ...*ResourceScopes) *ScopesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLionResourceScopeIDs(ids...)
}

// Mutation returns the ScopesMutation object of the builder.
func (_u *ScopesUpdateOne) Mutation() *ScopesMutation {
	return _u.mutation
}

// ClearLionResourceScopes clears all "lion_resource_scopes" edges to the ResourceScopes entity.
func (_u *ScopesUpdateOne) ClearLionResourceScopes() *ScopesUpdateOne {
	_u.mutation.ClearLionResourceScopes()
	return _u
}

// RemoveLionResourceScopeIDs removes the "lion_resource_scopes" edge to ResourceScopes entities by IDs.
func (_u *ScopesUpdateOne) RemoveLionResourceScopeIDs(ids ...int) *ScopesUpdateOne {
	_u.mutation.RemoveLionResourceScopeIDs(ids...)
	return _u
}

// RemoveLionResourceScopes removes "lion_resource_scopes" edges to ResourceScopes entities.
func (_u *ScopesUpdateOne) RemoveLionResourceScopes(v ...*ResourceScopes) *ScopesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLionResourceScopeIDs(ids...)
}

// Where appends a list predicates to the ScopesUpdate builder.
func (_u *ScopesUpdateOne) Where(ps ...predicate.Scopes) *ScopesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScopesUpdateOne) Select(field string, fields ...string) *ScopesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Scopes entity.
func (_u *ScopesUpdateOne) Save(ctx context.Context) (*Scopes, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScopesUpdateOne) SaveX(ctx context.Context) *Scopes {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScopesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScopesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScopesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scopes.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScopesUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scopes.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`lion: validator failed for field "Scopes.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ScopesUpdateOne) sqlSave(ctx context.Context) (_node *Scopes, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scopes.Table, scopes.Columns, sqlgraph.NewFieldSpec(scopes.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`lion: missing "Scopes.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scopes.FieldID)
		for _, f := range fields {
			if !scopes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("lion: invalid field %q for query", f)}
			}
			if f != scopes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scopes.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(scopes.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(scopes.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scopes.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(scopes.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLionResourceScopesIDs(); len(nodes) > 0 && !_u.mutation.LionResourceScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LionResourceScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scopes.LionResourceScopesTable,
			Columns: []string{scopes.LionResourceScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcescopes.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Scopes{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scopes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
