// Code generated by ent, DO NOT EDIT.

package lion

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/securitykeys"
)

// SecurityKeys is the model entity for the SecurityKeys schema.
type SecurityKeys struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 公钥 base64 编码存储
	PublicKey string `json:"public_key,omitempty"`
	// 私钥对称加密存储
	PrivateKeyEncrypted []byte `json:"-"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecurityKeys) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case securitykeys.FieldPrivateKeyEncrypted:
			values[i] = new([]byte)
		case securitykeys.FieldID:
			values[i] = new(sql.NullInt64)
		case securitykeys.FieldPublicKey:
			values[i] = new(sql.NullString)
		case securitykeys.FieldCreatedAt, securitykeys.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecurityKeys fields.
func (_m *SecurityKeys) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case securitykeys.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case securitykeys.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case securitykeys.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case securitykeys.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				_m.PublicKey = value.String
			}
		case securitykeys.FieldPrivateKeyEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_encrypted", values[i])
			} else if value != nil {
				_m.PrivateKeyEncrypted = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecurityKeys.
// This includes values selected through modifiers, order, etc.
func (_m *SecurityKeys) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SecurityKeys.
// Note that you need to call SecurityKeys.Unwrap() before calling this method if this SecurityKeys
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SecurityKeys) Update() *SecurityKeysUpdateOne {
	return NewSecurityKeysClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SecurityKeys entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SecurityKeys) Unwrap() *SecurityKeys {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: SecurityKeys is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SecurityKeys) String() string {
	var builder strings.Builder
	builder.WriteString("SecurityKeys(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(_m.PublicKey)
	builder.WriteString(", ")
	builder.WriteString("private_key_encrypted=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// SecurityKeysSlice is a parsable slice of SecurityKeys.
type SecurityKeysSlice []*SecurityKeys
