// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/userauthlocal"
)

// UserAuthLocalCreate is the builder for creating a UserAuthLocal entity.
type UserAuthLocalCreate struct {
	config
	mutation *UserAuthLocalMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAuthLocalCreate) SetCreatedAt(v time.Time) *UserAuthLocalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAuthLocalCreate) SetNillableCreatedAt(v *time.Time) *UserAuthLocalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAuthLocalCreate) SetUpdatedAt(v time.Time) *UserAuthLocalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAuthLocalCreate) SetNillableUpdatedAt(v *time.Time) *UserAuthLocalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserAuthLocalCreate) SetUserID(v int) *UserAuthLocalCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserAuthLocalCreate) SetPasswordHash(v []byte) *UserAuthLocalCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetMfaEnabled sets the "mfa_enabled" field.
func (_c *UserAuthLocalCreate) SetMfaEnabled(v bool) *UserAuthLocalCreate {
	_c.mutation.SetMfaEnabled(v)
	return _c
}

// SetNillableMfaEnabled sets the "mfa_enabled" field if the given value is not nil.
func (_c *UserAuthLocalCreate) SetNillableMfaEnabled(v *bool) *UserAuthLocalCreate {
	if v != nil {
		_c.SetMfaEnabled(*v)
	}
	return _c
}

// SetMfaSecretEncrypted sets the "mfa_secret_encrypted" field.
func (_c *UserAuthLocalCreate) SetMfaSecretEncrypted(v []byte) *UserAuthLocalCreate {
	_c.mutation.SetMfaSecretEncrypted(v)
	return _c
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_c *UserAuthLocalCreate) SetPasswordChangedAt(v time.Time) *UserAuthLocalCreate {
	_c.mutation.SetPasswordChangedAt(v)
	return _c
}

// SetNillablePasswordChangedAt sets the "password_changed_at" field if the given value is not nil.
func (_c *UserAuthLocalCreate) SetNillablePasswordChangedAt(v *time.Time) *UserAuthLocalCreate {
	if v != nil {
		_c.SetPasswordChangedAt(*v)
	}
	return _c
}

// SetPasswordExpiresAt sets the "password_expires_at" field.
func (_c *UserAuthLocalCreate) SetPasswordExpiresAt(v time.Time) *UserAuthLocalCreate {
	_c.mutation.SetPasswordExpiresAt(v)
	return _c
}

// SetNillablePasswordExpiresAt sets the "password_expires_at" field if the given value is not nil.
func (_c *UserAuthLocalCreate) SetNillablePasswordExpiresAt(v *time.Time) *UserAuthLocalCreate {
	if v != nil {
		_c.SetPasswordExpiresAt(*v)
	}
	return _c
}

// Mutation returns the UserAuthLocalMutation object of the builder.
func (_c *UserAuthLocalCreate) Mutation() *UserAuthLocalMutation {
	return _c.mutation
}

// Save creates the UserAuthLocal in the database.
func (_c *UserAuthLocalCreate) Save(ctx context.Context) (*UserAuthLocal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAuthLocalCreate) SaveX(ctx context.Context) *UserAuthLocal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthLocalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthLocalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAuthLocalCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userauthlocal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userauthlocal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MfaEnabled(); !ok {
		v := userauthlocal.DefaultMfaEnabled
		_c.mutation.SetMfaEnabled(v)
	}
	if _, ok := _c.mutation.MfaSecretEncrypted(); !ok {
		v := userauthlocal.DefaultMfaSecretEncrypted
		_c.mutation.SetMfaSecretEncrypted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAuthLocalCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "UserAuthLocal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "UserAuthLocal.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`lion: missing required field "UserAuthLocal.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userauthlocal.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`lion: validator failed for field "UserAuthLocal.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`lion: missing required field "UserAuthLocal.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := userauthlocal.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`lion: validator failed for field "UserAuthLocal.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MfaEnabled(); !ok {
		return &ValidationError{Name: "mfa_enabled", err: errors.New(`lion: missing required field "UserAuthLocal.mfa_enabled"`)}
	}
	if _, ok := _c.mutation.MfaSecretEncrypted(); !ok {
		return &ValidationError{Name: "mfa_secret_encrypted", err: errors.New(`lion: missing required field "UserAuthLocal.mfa_secret_encrypted"`)}
	}
	return nil
}

func (_c *UserAuthLocalCreate) sqlSave(ctx context.Context) (*UserAuthLocal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAuthLocalCreate) createSpec() (*UserAuthLocal, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAuthLocal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userauthlocal.Table, sqlgraph.NewFieldSpec(userauthlocal.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userauthlocal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userauthlocal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userauthlocal.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(userauthlocal.FieldPasswordHash, field.TypeBytes, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.MfaEnabled(); ok {
		_spec.SetField(userauthlocal.FieldMfaEnabled, field.TypeBool, value)
		_node.MfaEnabled = value
	}
	if value, ok := _c.mutation.MfaSecretEncrypted(); ok {
		_spec.SetField(userauthlocal.FieldMfaSecretEncrypted, field.TypeBytes, value)
		_node.MfaSecretEncrypted = value
	}
	if value, ok := _c.mutation.PasswordChangedAt(); ok {
		_spec.SetField(userauthlocal.FieldPasswordChangedAt, field.TypeTime, value)
		_node.PasswordChangedAt = &value
	}
	if value, ok := _c.mutation.PasswordExpiresAt(); ok {
		_spec.SetField(userauthlocal.FieldPasswordExpiresAt, field.TypeTime, value)
		_node.PasswordExpiresAt = &value
	}
	return _node, _spec
}

// UserAuthLocalCreateBulk is the builder for creating many UserAuthLocal entities in bulk.
type UserAuthLocalCreateBulk struct {
	config
	err      error
	builders []*UserAuthLocalCreate
}

// Save creates the UserAuthLocal entities in the database.
func (_c *UserAuthLocalCreateBulk) Save(ctx context.Context) ([]*UserAuthLocal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAuthLocal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAuthLocalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAuthLocalCreateBulk) SaveX(ctx context.Context) []*UserAuthLocal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthLocalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthLocalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
