// Code generated by ent, DO NOT EDIT.

package lion

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grpc-kit/pkg/lion/departments"
	"github.com/grpc-kit/pkg/lion/userdepartments"
	"github.com/grpc-kit/pkg/lion/users"
)

// UserDepartmentsCreate is the builder for creating a UserDepartments entity.
type UserDepartmentsCreate struct {
	config
	mutation *UserDepartmentsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserDepartmentsCreate) SetCreatedAt(v time.Time) *UserDepartmentsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableCreatedAt(v *time.Time) *UserDepartmentsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserDepartmentsCreate) SetUpdatedAt(v time.Time) *UserDepartmentsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableUpdatedAt(v *time.Time) *UserDepartmentsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UserDepartmentsCreate) SetCreatedBy(v int64) *UserDepartmentsCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableCreatedBy(v *int64) *UserDepartmentsCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *UserDepartmentsCreate) SetUpdatedBy(v int64) *UserDepartmentsCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableUpdatedBy(v *int64) *UserDepartmentsCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *UserDepartmentsCreate) SetDepartmentID(v int) *UserDepartmentsCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserDepartmentsCreate) SetUserID(v int) *UserDepartmentsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetMemberRole sets the "member_role" field.
func (_c *UserDepartmentsCreate) SetMemberRole(v int) *UserDepartmentsCreate {
	_c.mutation.SetMemberRole(v)
	return _c
}

// SetNillableMemberRole sets the "member_role" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableMemberRole(v *int) *UserDepartmentsCreate {
	if v != nil {
		_c.SetMemberRole(*v)
	}
	return _c
}

// SetMemberStatus sets the "member_status" field.
func (_c *UserDepartmentsCreate) SetMemberStatus(v int) *UserDepartmentsCreate {
	_c.mutation.SetMemberStatus(v)
	return _c
}

// SetNillableMemberStatus sets the "member_status" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableMemberStatus(v *int) *UserDepartmentsCreate {
	if v != nil {
		_c.SetMemberStatus(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *UserDepartmentsCreate) SetExpiredAt(v time.Time) *UserDepartmentsCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableExpiredAt(v *time.Time) *UserDepartmentsCreate {
	if v != nil {
		_c.SetExpiredAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *UserDepartmentsCreate) SetMetadata(v string) *UserDepartmentsCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableMetadata(v *string) *UserDepartmentsCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *UserDepartmentsCreate) SetDescription(v string) *UserDepartmentsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UserDepartmentsCreate) SetNillableDescription(v *string) *UserDepartmentsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLionDepartmentsID sets the "lion_departments" edge to the Departments entity by ID.
func (_c *UserDepartmentsCreate) SetLionDepartmentsID(id int) *UserDepartmentsCreate {
	_c.mutation.SetLionDepartmentsID(id)
	return _c
}

// SetLionDepartments sets the "lion_departments" edge to the Departments entity.
func (_c *UserDepartmentsCreate) SetLionDepartments(v *Departments) *UserDepartmentsCreate {
	return _c.SetLionDepartmentsID(v.ID)
}

// SetLionUsersID sets the "lion_users" edge to the Users entity by ID.
func (_c *UserDepartmentsCreate) SetLionUsersID(id int) *UserDepartmentsCreate {
	_c.mutation.SetLionUsersID(id)
	return _c
}

// SetLionUsers sets the "lion_users" edge to the Users entity.
func (_c *UserDepartmentsCreate) SetLionUsers(v *Users) *UserDepartmentsCreate {
	return _c.SetLionUsersID(v.ID)
}

// Mutation returns the UserDepartmentsMutation object of the builder.
func (_c *UserDepartmentsCreate) Mutation() *UserDepartmentsMutation {
	return _c.mutation
}

// Save creates the UserDepartments in the database.
func (_c *UserDepartmentsCreate) Save(ctx context.Context) (*UserDepartments, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserDepartmentsCreate) SaveX(ctx context.Context) *UserDepartments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDepartmentsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDepartmentsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserDepartmentsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userdepartments.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userdepartments.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := userdepartments.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		v := userdepartments.DefaultUpdatedBy
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.MemberRole(); !ok {
		v := userdepartments.DefaultMemberRole
		_c.mutation.SetMemberRole(v)
	}
	if _, ok := _c.mutation.MemberStatus(); !ok {
		v := userdepartments.DefaultMemberStatus
		_c.mutation.SetMemberStatus(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := userdepartments.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserDepartmentsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`lion: missing required field "UserDepartments.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`lion: missing required field "UserDepartments.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`lion: missing required field "UserDepartments.created_by"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`lion: missing required field "UserDepartments.updated_by"`)}
	}
	if _, ok := _c.mutation.DepartmentID(); !ok {
		return &ValidationError{Name: "department_id", err: errors.New(`lion: missing required field "UserDepartments.department_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`lion: missing required field "UserDepartments.user_id"`)}
	}
	if _, ok := _c.mutation.MemberRole(); !ok {
		return &ValidationError{Name: "member_role", err: errors.New(`lion: missing required field "UserDepartments.member_role"`)}
	}
	if _, ok := _c.mutation.MemberStatus(); !ok {
		return &ValidationError{Name: "member_status", err: errors.New(`lion: missing required field "UserDepartments.member_status"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`lion: missing required field "UserDepartments.description"`)}
	}
	if len(_c.mutation.LionDepartmentsIDs()) == 0 {
		return &ValidationError{Name: "lion_departments", err: errors.New(`lion: missing required edge "UserDepartments.lion_departments"`)}
	}
	if len(_c.mutation.LionUsersIDs()) == 0 {
		return &ValidationError{Name: "lion_users", err: errors.New(`lion: missing required edge "UserDepartments.lion_users"`)}
	}
	return nil
}

func (_c *UserDepartmentsCreate) sqlSave(ctx context.Context) (*UserDepartments, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserDepartmentsCreate) createSpec() (*UserDepartments, *sqlgraph.CreateSpec) {
	var (
		_node = &UserDepartments{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userdepartments.Table, sqlgraph.NewFieldSpec(userdepartments.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userdepartments.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userdepartments.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(userdepartments.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(userdepartments.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.MemberRole(); ok {
		_spec.SetField(userdepartments.FieldMemberRole, field.TypeInt, value)
		_node.MemberRole = value
	}
	if value, ok := _c.mutation.MemberStatus(); ok {
		_spec.SetField(userdepartments.FieldMemberStatus, field.TypeInt, value)
		_node.MemberStatus = value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(userdepartments.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(userdepartments.FieldMetadata, field.TypeString, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(userdepartments.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.LionDepartmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdepartments.LionDepartmentsTable,
			Columns: []string{userdepartments.LionDepartmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(departments.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LionUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdepartments.LionUsersTable,
			Columns: []string{userdepartments.LionUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserDepartmentsCreateBulk is the builder for creating many UserDepartments entities in bulk.
type UserDepartmentsCreateBulk struct {
	config
	err      error
	builders []*UserDepartmentsCreate
}

// Save creates the UserDepartments entities in the database.
func (_c *UserDepartmentsCreateBulk) Save(ctx context.Context) ([]*UserDepartments, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserDepartments, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserDepartmentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserDepartmentsCreateBulk) SaveX(ctx context.Context) []*UserDepartments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserDepartmentsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserDepartmentsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
