// Code generated by ent, DO NOT EDIT.

package lion

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grpc-kit/pkg/lion/users"
)

// Users is the model entity for the Users schema.
type Users struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 首选用户名，用于系统识别与登录，仅支持字母、数字、下划线、点号
	Username string `json:"username,omitempty"`
	// 用户的真实姓名
	RealnameEncrypted []byte `json:"-"`
	// 用户状态
	Status int `json:"status,omitempty"`
	// 用户身份证号码
	NationalIDEncrypted []byte `json:"-"`
	// 用户的身份证号码哈希，用于唯一值判断
	NationalIDHash string `json:"national_id_hash,omitempty"`
	// 用户的昵称，用于页面展示
	Nickname string `json:"nickname,omitempty"`
	// 用户个人简介等
	Profile string `json:"profile,omitempty"`
	// 用户头像的 URL
	Picture string `json:"picture,omitempty"`
	// 用户的个人网站 URL
	Website string `json:"website,omitempty"`
	// 用户的邮箱地址
	EmailEncrypted []byte `json:"-"`
	// 用户的邮箱地址哈希，用于唯一值判断
	EmailHash string `json:"email_hash,omitempty"`
	// 邮箱是否验证过
	EmailVerified bool `json:"email_verified,omitempty"`
	// 用户的性别，如：0, 1=male、2=female
	Gender int `json:"gender,omitempty"`
	// 用户的出生日期，格式为 YYYY-MM-DD，如 1990-12-31
	Birthdate time.Time `json:"birthdate,omitempty"`
	// 用户的时区信息，如：Asia/Shanghai
	Zoneinfo string `json:"zoneinfo,omitempty"`
	// 用户的语言/地区偏好，如：zh-CN
	Locale string `json:"locale,omitempty"`
	// 用户的手机号码，加密存储
	PhoneNumberEncrypted []byte `json:"-"`
	// 用户的手机号哈希，用于唯一值判断
	PhoneNumberHash string `json:"phone_number_hash,omitempty"`
	// 手机号是否验证过
	PhoneNumberVerified bool `json:"phone_number_verified,omitempty"`
	// 用户的地址信息
	AddressEncrypted []byte `json:"-"`
	// 部门 ID
	DepartmentID int `json:"department_id,omitempty"`
	// 用户详细描述
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsersQuery when eager-loading is set.
	Edges        UsersEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsersEdges holds the relations/edges for other nodes in the graph.
type UsersEdges struct {
	// LionUserRoles holds the value of the lion_user_roles edge.
	LionUserRoles []*UserRoles `json:"lion_user_roles,omitempty"`
	// LionUserIdentities holds the value of the lion_user_identities edge.
	LionUserIdentities []*UserIdentities `json:"lion_user_identities,omitempty"`
	// LionUserDepartments holds the value of the lion_user_departments edge.
	LionUserDepartments []*UserDepartments `json:"lion_user_departments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// LionUserRolesOrErr returns the LionUserRoles value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) LionUserRolesOrErr() ([]*UserRoles, error) {
	if e.loadedTypes[0] {
		return e.LionUserRoles, nil
	}
	return nil, &NotLoadedError{edge: "lion_user_roles"}
}

// LionUserIdentitiesOrErr returns the LionUserIdentities value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) LionUserIdentitiesOrErr() ([]*UserIdentities, error) {
	if e.loadedTypes[1] {
		return e.LionUserIdentities, nil
	}
	return nil, &NotLoadedError{edge: "lion_user_identities"}
}

// LionUserDepartmentsOrErr returns the LionUserDepartments value or an error if the edge
// was not loaded in eager-loading.
func (e UsersEdges) LionUserDepartmentsOrErr() ([]*UserDepartments, error) {
	if e.loadedTypes[2] {
		return e.LionUserDepartments, nil
	}
	return nil, &NotLoadedError{edge: "lion_user_departments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Users) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case users.FieldRealnameEncrypted, users.FieldNationalIDEncrypted, users.FieldEmailEncrypted, users.FieldPhoneNumberEncrypted, users.FieldAddressEncrypted:
			values[i] = new([]byte)
		case users.FieldEmailVerified, users.FieldPhoneNumberVerified:
			values[i] = new(sql.NullBool)
		case users.FieldID, users.FieldStatus, users.FieldGender, users.FieldDepartmentID:
			values[i] = new(sql.NullInt64)
		case users.FieldUsername, users.FieldNationalIDHash, users.FieldNickname, users.FieldProfile, users.FieldPicture, users.FieldWebsite, users.FieldEmailHash, users.FieldZoneinfo, users.FieldLocale, users.FieldPhoneNumberHash, users.FieldDescription:
			values[i] = new(sql.NullString)
		case users.FieldCreatedAt, users.FieldUpdatedAt, users.FieldDeletedAt, users.FieldBirthdate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Users fields.
func (_m *Users) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case users.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case users.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case users.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case users.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case users.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case users.FieldRealnameEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field realname_encrypted", values[i])
			} else if value != nil {
				_m.RealnameEncrypted = *value
			}
		case users.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case users.FieldNationalIDEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field national_id_encrypted", values[i])
			} else if value != nil {
				_m.NationalIDEncrypted = *value
			}
		case users.FieldNationalIDHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field national_id_hash", values[i])
			} else if value.Valid {
				_m.NationalIDHash = value.String
			}
		case users.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = value.String
			}
		case users.FieldProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value.Valid {
				_m.Profile = value.String
			}
		case users.FieldPicture:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field picture", values[i])
			} else if value.Valid {
				_m.Picture = value.String
			}
		case users.FieldWebsite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website", values[i])
			} else if value.Valid {
				_m.Website = value.String
			}
		case users.FieldEmailEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field email_encrypted", values[i])
			} else if value != nil {
				_m.EmailEncrypted = *value
			}
		case users.FieldEmailHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_hash", values[i])
			} else if value.Valid {
				_m.EmailHash = value.String
			}
		case users.FieldEmailVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_verified", values[i])
			} else if value.Valid {
				_m.EmailVerified = value.Bool
			}
		case users.FieldGender:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = int(value.Int64)
			}
		case users.FieldBirthdate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field birthdate", values[i])
			} else if value.Valid {
				_m.Birthdate = value.Time
			}
		case users.FieldZoneinfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zoneinfo", values[i])
			} else if value.Valid {
				_m.Zoneinfo = value.String
			}
		case users.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case users.FieldPhoneNumberEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number_encrypted", values[i])
			} else if value != nil {
				_m.PhoneNumberEncrypted = *value
			}
		case users.FieldPhoneNumberHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number_hash", values[i])
			} else if value.Valid {
				_m.PhoneNumberHash = value.String
			}
		case users.FieldPhoneNumberVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number_verified", values[i])
			} else if value.Valid {
				_m.PhoneNumberVerified = value.Bool
			}
		case users.FieldAddressEncrypted:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field address_encrypted", values[i])
			} else if value != nil {
				_m.AddressEncrypted = *value
			}
		case users.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = int(value.Int64)
			}
		case users.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Users.
// This includes values selected through modifiers, order, etc.
func (_m *Users) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLionUserRoles queries the "lion_user_roles" edge of the Users entity.
func (_m *Users) QueryLionUserRoles() *UserRolesQuery {
	return NewUsersClient(_m.config).QueryLionUserRoles(_m)
}

// QueryLionUserIdentities queries the "lion_user_identities" edge of the Users entity.
func (_m *Users) QueryLionUserIdentities() *UserIdentitiesQuery {
	return NewUsersClient(_m.config).QueryLionUserIdentities(_m)
}

// QueryLionUserDepartments queries the "lion_user_departments" edge of the Users entity.
func (_m *Users) QueryLionUserDepartments() *UserDepartmentsQuery {
	return NewUsersClient(_m.config).QueryLionUserDepartments(_m)
}

// Update returns a builder for updating this Users.
// Note that you need to call Users.Unwrap() before calling this method if this Users
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Users) Update() *UsersUpdateOne {
	return NewUsersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Users entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Users) Unwrap() *Users {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("lion: Users is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Users) String() string {
	var builder strings.Builder
	builder.WriteString("Users(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("realname_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("national_id_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("national_id_hash=")
	builder.WriteString(_m.NationalIDHash)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(_m.Profile)
	builder.WriteString(", ")
	builder.WriteString("picture=")
	builder.WriteString(_m.Picture)
	builder.WriteString(", ")
	builder.WriteString("website=")
	builder.WriteString(_m.Website)
	builder.WriteString(", ")
	builder.WriteString("email_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("email_hash=")
	builder.WriteString(_m.EmailHash)
	builder.WriteString(", ")
	builder.WriteString("email_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailVerified))
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gender))
	builder.WriteString(", ")
	builder.WriteString("birthdate=")
	builder.WriteString(_m.Birthdate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("zoneinfo=")
	builder.WriteString(_m.Zoneinfo)
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("phone_number_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("phone_number_hash=")
	builder.WriteString(_m.PhoneNumberHash)
	builder.WriteString(", ")
	builder.WriteString("phone_number_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.PhoneNumberVerified))
	builder.WriteString(", ")
	builder.WriteString("address_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// UsersSlice is a parsable slice of Users.
type UsersSlice []*Users
